-- ============================================================
-- PRODUCTS TABLE (SKU master list for dropdown)
-- ============================================================

CREATE TABLE IF NOT EXISTS products (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sku_code TEXT UNIQUE NOT NULL,
  sku_name TEXT NOT NULL DEFAULT '',
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_products_sku_code ON products(sku_code);
CREATE INDEX IF NOT EXISTS idx_products_active ON products(is_active) WHERE is_active = true;

-- RLS
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
CREATE POLICY products_select ON products FOR SELECT USING (true);

INSERT INTO products (sku_code, sku_name) VALUES
  ('115.884.00.1', 'Geberit Sigma21 Custom Plate Mechanism'),
  ('115.884.00.1-CH', 'Sigma 21 Dual Flush Plate by Geberit'),
  ('115.884.00.1-PVDBB', 'Sigma 21 Dual Flush Plate by Geberit'),
  ('115.884.00.1-PVDBN', 'Sigma 21 Dual Flush Plate by Geberit'),
  ('115.884.00.1-PVDGM', 'Geberit Sigma21 Dual Flush Plate -'),
  ('115.884.00.1N-CH', 'Meir Sigma 21 Dual Flush Plates for Geberit'),
  ('115.884.00.1N-PVDBB', 'Meir Sigma 21 Dual Flush Plates for Geberit'),
  ('115.884.00.1N-PVDBN', 'Meir Sigma 21 Dual Flush Plates for Geberit'),
  ('115.884.00.1N-PVDBZ', 'Meir Sigma 21 Dual Flush Plates for Geberit'),
  ('115.884.00.1N-PVDGM', 'Meir Sigma 21 Dual Flush Plates for Geberit'),
  ('BOARD-BT-ACC-EXISTINGSTORE', 'Beaumont Tiles Display Board XXX BOARD-BT-PLAIN + 10 x FIT-ACC + 1 x KPFIT-ACC'),
  ('BOARD-BT-PLAIN', 'Beaumont Tiles Display Board XXX Plain Board (not drilled)'),
  ('BOARD-BT-SHOWER-EXISTINGSTORE', 'Beaumont Tiles Display Board XXX 1 x BOARD-BT-PLAIN + 2 x MPWT01'),
  ('BOARD-BT-SINGLESHOWER-NEWSTORE', 'BT Single Shower Display Board XXX 1 x BOARD-BT-PLAIN-THIN + 1 x MPWT01'),
  ('BOARD-BT-TAP-EXISTINGSTORE', 'Beaumont Tiles Display TAP Board with Hob XXX 1 x BOARD-BT-PLAIN + 1 x HOB-BT + 2 x MPWT01 + 2 x DMW-PART1 + 2 x P027006-01'),
  ('BOARD-BT-TAP-OPTIONONE-NEWSTORE', 'BT Display TAP Board Option 1: 1 x BOARD-BT-PLAIN + 5 x MPWT01 + 4 x DMW-PART1'),
  ('BOARD-BT-TWINSHOWER-NEWSTORE', 'BT Twin Shower Display Board XXX 1 x BOARD-BT-PLAIN-THIN + 1 x MPWT01'),
  ('BOARD-DOUBLE (NO FITTINGS)', 'Floor Standing Double Sided Display Board (NO FITTINGS)'),
  ('BOARD-SINGLE (NO FITTINGS)', 'Single Sided Floor Standing or Wall Hung Display Board XXX With No Fittings'),
  ('BOARD-SINGLE01(WITHFITTINGS)', 'Single Sided Floor Standing or Wall Hung Display Board XXX With Fittings 01'),
  ('BOARD-DOUBLE01(WITHFITTINGS)', 'Floor Standing Double Sided Display Board (WITH FITTINGS) 2'),
  ('BOARD-SINGLE02(WITHFITTINGS)', 'Single Sided Floor Standing or Wall Hung Display Board XXX With Fittings 01'),
  ('BOARD-DOUBLE02(WITHFITTINGS)', 'Floor Standing Double Sided Display Board (WITH FITTINGS) 2'),
  ('BOART-BT-ACC-NEWSTORE', 'BT Display Board XXX 1 x BOARD-BT-PLAIN + 11 x FIT-ACC + 1 x KPFIT-ACC'),
  ('DDT-01-GM', 'Dish Draining Tray'),
  ('DDT-01-NK', 'Dish Draining Tray'),
  ('DDT-01-PVDBB', 'Dish Draining Tray'),
  ('DDT-01-PVDBN', 'Dish Draining Tray'),
  ('DDT-01-PVDGM', 'Dish Draining Tray'),
  ('DIV-FIT', 'Display board mount for diverter Handle XXX P043309-Z5'),
  ('DMA09-400-PVDGM', 'Dummy Round Wall Shower Curved Arm 400mm XXX'),
  ('DMB01', 'Matte Bathroom Mixer Tap Dummy'),
  ('DMB02', 'Matte Bathroom Mixer Dummy'),
  ('DMB02-C', 'Dummy Basin mixer'),
  ('DMB02-CH', 'Dummy Basin mixer'),
  ('DMB02-PVDBB', 'Dummy Basin mixer'),
  ('DMB02-PVDBN', 'Dummy Basin mixer'),
  ('DMB02-PVDBZ', 'Dummy Basin mixer'),
  ('DMB02-PVDGM', 'Dummy Basin mixer'),
  ('DMB02PD', 'Dummy Basin Mixer with Paddle Handle'),
  ('DMB02PD-CH', 'Dummy Basin Mixer with Paddle Handle'),
  ('DMB02PD-PVDBB', 'Dummy Basin Mixer with Paddle Handle'),
  ('DMB02PD-PVDBN', 'Dummy Basin Mixer with Paddle Handle'),
  ('DMB02PD-PVDBZ', 'Dummy Basin Mixer with Paddle Handle'),
  ('DMB02PD-PVDGM', 'Dummy Basin Mixer with Paddle Handle'),
  ('DMB02PN', 'Dummy Basin Mixer with Pinless Handle'),
  ('DMB02PN-CH', 'Dummy Basin Mixer with Pinless Handle'),
  ('DMB02PN-PVDBB', 'Dummy Basin Mixer with Pinless Handle'),
  ('DMB02PN-PVDBN', 'Dummy Basin Mixer with Pinless Handle'),
  ('DMB02PN-PVDGM', 'Dummy Basin Mixer with Pinless Handle')
ON CONFLICT (sku_code) DO UPDATE SET sku_name = EXCLUDED.sku_name;

INSERT INTO products (sku_code, sku_name) VALUES
  ('DMB03', 'Matte Bathroom Mixer'),
  ('DMB03-CH', 'Round Masin Mixer Curved XXX Dummy'),
  ('DMB03-PVDBB', 'Round Masin Mixer Curved XXX Dummy'),
  ('DMB03-PVDBN', 'Round Masin Mixer Curved XXX Dummy'),
  ('DMB03-PVDGM', 'Round Masin Mixer Curved XXX Dummy'),
  ('DMB03XL.01', 'Piccola Tall Masin Mixer Tap with 130mm Spout XXX Dummy'),
  ('DMB03XL.01-CH', 'Piccola Tall Masin Mixer Tap with 130mm Spout XXX Dummy'),
  ('DMB03XL.01-PVDBB', 'Piccola Tall Masin Mixer Tap with 130mm Spout XXX Dummy'),
  ('DMB03XS', 'Piccola Basin Mixer Tap Dummy'),
  ('DMB03XS-CH', 'Piccola Basin Mixer Tap Dummy'),
  ('DMB03XS-PVDBB', 'Piccola Basin Mixer Tap Dummy'),
  ('DMB03XS-PVDBN', 'Piccola Basin Mixer Tap Dummy'),
  ('DMB03XS-PVDGM', 'Piccola Basin Mixer Tap Dummy'),
  ('DMB04', 'Tall Round Basin Mixer Dummy'),
  ('DMB04-R2', 'Tall Round Basin Mixer Dummy'),
  ('DMH04-PVDGM', 'Dummy Round Shower Rose 200mm'),
  ('DMK02', 'Round Matte Kitchen Mixer Dummy'),
  ('DMK02-CH', 'Round Kitchen Mixer Tap XXX Dummy'),
  ('DMK02-PVDBB', 'Round Kitchen Mixer Tap XXX Dummy'),
  ('DMK02-PVDGM', 'Round Kitchen Mixer Tap XXX Dummy'),
  ('DMK03', 'Round Kitchen Mixer Dummy'),
  ('DMK17-PVDGM', 'Dummy Piccola Out Kitchen Mixer Tap'),
  ('DMQ04', 'Meir Cut Down Spindle MW11 Display (single)'),
  ('DMR01-R', '600mm Round Double Towel Rail Dummy'),
  ('DMR01-R-PVDGM', '600mm Round Double Towel Rail Dummy'),
  ('DMR02', 'Matte Toilet Roll Holder Dummy'),
  ('DMR02-R', 'Matte Toilet Roll Holder Dummy'),
  ('DMR02-R-PVDGM', 'Matte Toilet Roll Holder Dummy'),
  ('DMR03', 'Matte Robe Hook Dummy'),
  ('DMR03-R', 'Matte Robe Hook Dummy'),
  ('DMR03-R-PVDGM', 'Matte Robe Hook Dummy'),
  ('DMR05', 'Matte Guest Towel Rail Dummy'),
  ('DMR05-R', 'Matte Guest Towel Rail Dummy'),
  ('DMR05-R-PVDGM', 'Matte Guest Towel Rail Dummy'),
  ('DMS05', 'Matte Universal Curved Spout XXX Round Dummy'),
  ('DMS05-130-PVDGM', 'Matte Universal Curved Spout 130mm XXX Round Dummy'),
  ('DMS05-PVDGM', 'Matte Universal Curved Spout XXX Round Dummy'),
  ('DMTV02', 'Dummy Fitting for Two-Way Thermostatic Shower Mixer Valve with Diverter'),
  ('DMW-PART1', 'Mounting Display Fittings and Screw for wall mixers such as MW01, MW02, MW03, MW07 and MW07TS (use x1 per Mixer)'),
  ('DMW02-DIP', 'Diverter Knob Display Fitting Parts for MW02, MW07, MW07TS (Also need to use DMW-Part1)'),
  ('DMW08JL-PVDGM', 'Dummy Cross Handle Jumper Valve Wall Top Assemblies'),
  ('DMW11', 'Dummy XXX Round Wall Top Assemblies'),
  ('DMW11-CH', 'Dummy XXX Round Wall Top Assemblies'),
  ('DMW11-PVDBB', 'Dummy XXX Round Wall Top Assemblies'),
  ('DMW11-PVDBN', 'Dummy XXX Round Wall Top Assemblies'),
  ('DMW11-PVDGM', 'Dummy XXX Round Wall Top Assemblies'),
  ('DMZ0402-R-C', 'Dummy Round Combination Shower Rail 200mm Rose, Single Function Hand Shower'),
  ('DMZ0704-CH', 'Dummy Round Combination Shower Rail 200mm Rose, Three Function Hand Shower'),
  ('DMZ0704-R-CH', 'Dummy Round Combination Shower Rail 200mm Rose, Single Function Hand Shower'),
  ('DMZ0704-R-PVDGM', 'Dummy Round Combination Shower Rail 200mm Rose, Single Function Hand Shower')
ON CONFLICT (sku_code) DO UPDATE SET sku_name = EXCLUDED.sku_name;

INSERT INTO products (sku_code, sku_name) VALUES
  ('DMZ0706-CH', 'Dummy Round Combination Shower Rail 300mm Rose, Three Function Hand Shower'),
  ('DMZ0706-R-CH', 'Dummy Round Combination Shower Rail 300mm Rose, Single Function Hand Shower'),
  ('DMZ0706-R-PVDGM', 'Dummy Round Combination Shower Rail 300mm Rose, Single Function Hand Shower XXX'),
  ('DMZ08-R-PVDGM', 'Dummy Round Hand Shower on Fixed Bracket'),
  ('FIT-ACC', 'Fitting for Accessories on display Boards XXX P605107'),
  ('GRID-01', 'Lavello Protection Grid for MKSP-S380440'),
  ('GRID-01-GM', 'Lavello Protection Grid for MKSP-S380440'),
  ('GRID-01-PVDBB', 'Lavello Protection Grid for MKSP-S380440'),
  ('GRID-01-PVDGM', 'Lavello Protection Grid for MKSP-S380440'),
  ('GRID-02', 'Lavello Protection Grid for MKSP-S450450'),
  ('GRID-02-GM', 'Lavello Protection Grid for MKSP-S450450'),
  ('GRID-02-PVDBB', 'Lavello Protection Grid for MKSP-S450450'),
  ('GRID-02-PVDGM', 'Lavello Protection Grid for MKSP-S450450'),
  ('GRID-03', 'Lavello Protection Grid for MKSP-D860440 (2pcs)'),
  ('GRID-03-GM', 'Lavello Protection Grid for MKSP-D860440 (2pcs)'),
  ('GRID-03-PVDBB', 'Lavello Protection Grid for MKSP-D860440 (2pcs)'),
  ('GRID-03-PVDGM', 'Lavello Protection Grid for MKSP-D860440 (2pcs)'),
  ('GRID-04', 'Lavello Protection Grid for MKSP-D670440 (2pcs)'),
  ('GRID-04-GM', 'Lavello Protection Grid for MKSP-D670440 (2pcs)'),
  ('GRID-04-PVDBB', 'Lavello Protection Grid for MKSP-D670440 (2pcs)'),
  ('GRID-04-PVDGM', 'Lavello Protection Grid for MKSP-D670440 (2pcs)'),
  ('GRID-05', 'Lavello Protection Grid for MKSP-D760440 (2pcs)'),
  ('GRID-05-GM', 'Lavello Protection Grid for MKSP-D760440 (2pcs)'),
  ('GRID-05-PVDBB', 'Lavello Protection Grid for MKSP-D760440 (2pcs)'),
  ('GRID-05-PVDGM', 'Lavello Protection Grid for MKSP-D760440 (2pcs)'),
  ('GRID-06', 'Lavello Protection Grid for MKSP-D1160440D (2pcs)'),
  ('GRID-06-GM', 'Lavello Protection Grid for MKSP-D1160440D (2pcs)'),
  ('GRID-06-PVDBB', 'Lavello Protection Grid for MKSP-D1160440D (2pcs)'),
  ('GRID-06-PVDGM', 'Lavello Protection Grid for MKSP-D1160440D (2pcs)'),
  ('GRID-07', 'Lavello Protection Grid for MKSP-S840440D'),
  ('GRID-07-GM', 'Lavello Protection Grid for MKSP-S840440D'),
  ('GRID-07-PVDBB', 'Lavello Protection Grid for MKSP-S840440D'),
  ('GRID-07-PVDGM', 'Lavello Protection Grid for MKSP-S840440D'),
  ('GRID-08', 'Lavello Protection Grid for MKSP-S760440'),
  ('GRID-08-GM', 'Lavello Protection Grid for MKSP-S760440'),
  ('GRID-08-PVDBB', 'Lavello Protection Grid for MKSP-S760440'),
  ('GRID-08-PVDGM', 'Lavello Protection Grid for MKSP-S760440'),
  ('GRID-09', 'Lavello Protection Grid for MKSP-S322222'),
  ('GRID-09-PVDBB', 'Lavello Protection Grid for MKSP-S322222'),
  ('GRID-09-PVDGM', 'Lavello Protection Grid for MKSP-S322222'),
  ('HA09-PVDBN', 'Harrington Shower Arm'),
  ('HB03-PVDBN', 'Harrington Short Basin Mixer'),
  ('HB04-R3-PVDBN', 'Harrington Basin Mixer'),
  ('HB08-PVDBN', 'Harrington Freestanding Bath Filler'),
  ('HB13-F-PVDBN', 'Harrington Three Hole Basin Set with Lever Handle'),
  ('HH04-PVDBN', 'Harrington Shower Head'),
  ('HINGE-DP01-1', 'Hinges for freestanding A-frame display for mini sinks'),
  ('HK03-PVDBN', 'Harrington Kitchen Mixer'),
  ('HOB-BATH', 'Floor Spout Hob'),
  ('HOB-BT', 'BT Hob for BT Display Boards')
ON CONFLICT (sku_code) DO UPDATE SET sku_name = EXCLUDED.sku_name;

INSERT INTO products (sku_code, sku_name) VALUES
  ('HOB-L', 'Large Grey Hob for Floor Standing Display Boards'),
  ('HR01-R-PVDBN', 'Harrington Double Towel Rail'),
  ('HR02-R-PVDBN', 'Harrington Toilet roll holder'),
  ('HR03-R-PVDBN', 'Harrington Robe Hook'),
  ('HR05-R-PVDBN', 'Harrington guest towel rail'),
  ('HS05-PVDBN', 'Harrington Wall Spout'),
  ('HS07-PVDBN', 'Harrington Wall Mount Swivel Spout'),
  ('HW03-FIN-PVDBN', 'Harrington Shower mixer finished parts'),
  ('HW06-PVDBN', 'Harrington Wall Tap Set with Lever Handle'),
  ('HW07TS-FIN-PVDBN', 'Harrington Shower divertor mixer finished parts'),
  ('HZ06-PVDBN', 'Harrington Shower on a Swivel Bracket'),
  ('HZ0704-PVDBN', 'Harrington Shower Rail Set'),
  ('MA0102-C', 'Square Wall Shower 200mm rose, 300mm arm'),
  ('MA0102-PVDBN', 'Square Wall Shower 200mm rose, 300mm arm'),
  ('MA0103', 'Square Wall Shower 300mm rose, 400mm arm'),
  ('MA02-300-P', 'Shower Arm Plate for MA0204 300mm arm and MS03 back plate'),
  ('MA02-300-P-BB', 'Shower Arm Plate for MA0204 300mm arm and MS03 back plate'),
  ('MA02-300-P-C', 'Shower Arm Plate for MA0204 300mm arm and MS03 back plate'),
  ('MA02-300-P-CH', 'Shower Arm Plate for MA0204 300mm arm and MS03 back plate'),
  ('MA02-300-PVDBB', 'Round Wall shower arm 300mm'),
  ('MA02-300-PVDBN', 'Round Wall shower arm 300mm'),
  ('MA02-400', 'Round Wall Shower Arm 400mm'),
  ('MA02-400-C', 'Round Wall Shower Arm 400mm'),
  ('MA02-400-CH', 'Round Wall Shower Arm 400mm'),
  ('MA02-400-P', 'Shower Arm Back Plate'),
  ('MA02-400-P-CH', 'Shower Arm Back Plate'),
  ('MA02-400-P-PVDBB', 'Shower Arm Back Plate'),
  ('MA02-400-P-PVDBN', 'Shower Arm Back Plate'),
  ('MA02-400-PVDBB', 'Round Wall Shower Arm 400mm'),
  ('MA02-400-PVDBN', 'Round Wall Shower Arm 400mm'),
  ('MA02-400-PVDBZ', 'Round Wall Shower Arm 400mm'),
  ('MA02-400-PVDGM', 'Round Wall Shower Arm 400mm'),
  ('MA07-150', 'Round Ceiling Shower Arm 150mm'),
  ('MA07-150-C', 'Round Ceiling Shower Arm 150mm'),
  ('MA07-150-CH', 'Round Ceiling Shower Arm 150mm'),
  ('MA07-150-PVDBB', 'Round Ceiling Shower Arm 150mm'),
  ('MA07-150-PVDBN', 'Round Ceiling Shower Arm 150mm'),
  ('MA07-150-PVDBZ', 'Round Ceiling Shower Arm 150mm'),
  ('MA07-150-PVDGM', 'Round Ceiling Shower Arm 150mm'),
  ('MA07-300', 'Round Ceiling Shower Arm 300mm'),
  ('MA07-300-C', 'Round Ceiling Shower Arm 300mm'),
  ('MA07-300-CH', 'Round Ceiling Shower Arm 300mm'),
  ('MA07-300-PVDBB', 'Round Ceiling Shower Arm 300mm'),
  ('MA07-300-PVDBN', 'Round Ceiling Shower Arm 300mm'),
  ('MA07-300-PVDBZ', 'Round Ceiling Shower Arm 300mm'),
  ('MA07-300-PVDGM', 'Round Ceiling Shower Arm 300mm'),
  ('MA0704-150-CH', 'Round Ceiling Shower 200mm rose, 150mm dropper'),
  ('MA0704-C', 'Round Ceiling Shower 200mm rose, 300mm dropper'),
  ('MA0704-P', 'Back Plate for MA0704'),
  ('MA0706-PVDBN', 'Round Ceiling Shower 300mm Rose, 300mm Dropper')
ON CONFLICT (sku_code) DO UPDATE SET sku_name = EXCLUDED.sku_name;

INSERT INTO products (sku_code, sku_name) VALUES
  ('MA09-300-C', 'Round Wall Shower Curved Arm 300mm'),
  ('MA09-300-PVDBN', 'Round Wall Shower Curved Arm 300mm'),
  ('MA09-400', 'Round Wall Shower Curved Arm 400mm'),
  ('MA09-400-BOX', 'MA09-400 XXX BOX'),
  ('MA09-400-C', 'Round Wall Shower Curved Arm 400mm'),
  ('MA09-400-CH', 'Round Wall Shower Curved Arm 400mm'),
  ('MA09-400-PVDBB', 'Round Wall Shower Curved Arm 400mm'),
  ('MA09-400-PVDBN', 'Round Wall Shower Curved Arm 400mm'),
  ('MA09-400-PVDBZ', 'Round Wall Shower Curved Arm 400mm'),
  ('MA09-400-PVDGM', 'Round Wall Shower Curved Arm 400mm'),
  ('MA0904-C', 'Round Wall Shower 200mm rose, 300mm curved arm'),
  ('MA0904-P', 'Shower Arm Plate for MA0904'),
  ('MA0904-P-C', 'Shower Arm Plate for MA0904'),
  ('MA0904-P-CH', 'Shower Arm Plate for MA0904'),
  ('MA0904-P-PVDBB', 'Shower Arm Plate for MA0904'),
  ('MA0904-P-PVDBN', 'Shower Arm Plate for MA0904'),
  ('MA10N-400-SS316', 'Outdoor Shower Arm 400mm XXX SS316'),
  ('MA10N-P-SS316', 'Shower Arm Back plate'),
  ('MA11', 'High Rise Shower Arm'),
  ('MA11-C', 'High Rise Shower Arm'),
  ('MA11-CH', 'High Rise Shower Arm'),
  ('MA11-PVDBB', 'High Rise Shower Arm'),
  ('MA11-PVDBN', 'High Rise Shower Arm'),
  ('MA11-PVDBZ', 'High Rise Shower Arm'),
  ('MA11-PVDGM', 'High Rise Shower Arm'),
  ('MB02', 'Round Basin Mixer'),
  ('MB02-C', 'Round Basin Mixer'),
  ('MB02-CH', 'Round Basin Mixer'),
  ('MB02-PVDBB', 'Round Basin Mixer'),
  ('MB02-PVDBN', 'Round Basin Mixer'),
  ('MB02-PVDBZ', 'Round Basin Mixer'),
  ('MB02-PVDGM', 'Round Basin Mixer'),
  ('MB02PD', 'Round Paddle Basin Mixer'),
  ('MB02PD-C', 'Round Paddle Basin Mixer'),
  ('MB02PD-CH', 'Round Paddle Basin Mixer'),
  ('MB02PD-PVDBB', 'Round Paddle Basin Mixer'),
  ('MB02PD-PVDBN', 'Round Paddle Basin Mixer'),
  ('MB02PD-PVDBZ', 'Round Paddle Basin Mixer'),
  ('MB02PD-PVDGM', 'Round Paddle Basin Mixer'),
  ('MB02PN', 'Round Pinless Basin Mixer'),
  ('MB02PN-C', 'Round Pinless Basin Mixer'),
  ('MB02PN-CH', 'Round Pinless Basin Mixer'),
  ('MB02PN-PVDBB', 'Round Pinless Basin Mixer'),
  ('MB02PN-PVDBN', 'Round Pinless Basin Mixer'),
  ('MB02PN-PVDBZ', 'Round Pinless Basin Mixer'),
  ('MB02PN-PVDGM', 'Round Pinless Basin Mixer'),
  ('MB03', 'Round Basin Mixer Curved'),
  ('MB03-C', 'Round Basin Mixer Curved'),
  ('MB03-CH', 'Round Basin Mixer Curved'),
  ('MB03-PVDBB', 'Round Basin Mixer Curved')
ON CONFLICT (sku_code) DO UPDATE SET sku_name = EXCLUDED.sku_name;

INSERT INTO products (sku_code, sku_name) VALUES
  ('MB03-PVDBN', 'Round Basin Mixer Curved'),
  ('MB03-PVDBZ', 'Round Basin Mixer Curved'),
  ('MB03-PVDGM', 'Round Basin Mixer Curved'),
  ('MB03XL.01', 'Piccola Tall Basin Mixer Tap with 130mm Spout'),
  ('MB03XL.01-C', 'Piccola Tall Basin Mixer Tap with 130mm Spout'),
  ('MB03XL.01-CH', 'Piccola Tall Basin Mixer Tap with 130mm Spout'),
  ('MB03XL.01-PVDBZ', 'Piccola Tall Basin Mixer Tap with 130mm Spout'),
  ('MB03XL.01-PVDGM', 'Piccola Tall Basin Mixer Tap with 130mm Spout'),
  ('MB03XS', 'Piccola Basin Mixer Tap'),
  ('MB03XS-C', 'Piccola Basin Mixer Tap'),
  ('MB03XS-CH', 'Piccola Basin Mixer Tap'),
  ('MB03XS-PVDBB', 'Piccola Basin Mixer Tap'),
  ('MB03XS-PVDBN', 'Piccola Basin Mixer Tap'),
  ('MB03XS-PVDBZ', 'Piccola Basin Mixer Tap'),
  ('MB03XS-PVDGM', 'Piccola Basin Mixer Tap'),
  ('MB04-R2', 'Round Tall Basin Mixer'),
  ('MB04-R2-C', 'Round Tall Basin Mixer'),
  ('MB04-R2-CH', 'Round Tall Basin Mixer'),
  ('MB04-R2-H', 'Basin mixer handle'),
  ('MB04-R2-PVDBB', 'Round Tall Basin Mixer'),
  ('MB04-R2-PVDBN', 'Round Tall Basin Mixer'),
  ('MB04-R2-PVDBZ', 'Round Tall Basin Mixer'),
  ('MB04-R2-PVDGM', 'Round Tall Basin Mixer'),
  ('MB04-R3', 'Round Tall Curved Basin Mixer'),
  ('MB04-R3-C', 'Round Tall Curved Basin Mixer'),
  ('MB04-R3-CH', 'Round Tall Curved Basin Mixer'),
  ('MB04-R3-PVDBB', 'Round Tall Curved Basin Mixer'),
  ('MB04-R3-PVDBN', 'Round Tall Curved Basin Mixer'),
  ('MB04-R3-PVDBZ', 'Round Tall Basin Mixer Curved'),
  ('MB04-R3-PVDGM', 'Round Tall Curved Basin Mixer'),
  ('MB04PD-R2', 'Round Paddle Tall Basin Mixer'),
  ('MB04PD-R2-C', 'Round Paddle Tall Basin Mixer'),
  ('MB04PD-R2-CH', 'Round Paddle Tall Basin Mixer'),
  ('MB04PD-R2-PVDBB', 'Round Paddle Tall Basin Mixer'),
  ('MB04PD-R2-PVDBN', 'Round Paddle Tall Basin Mixer'),
  ('MB04PD-R2-PVDBZ', 'Round Paddle Tall Basin Mixer'),
  ('MB04PD-R2-PVDGM', 'Round Paddle Tall Basin Mixer'),
  ('MB04PN-R2', 'Round Pinless Tall Basin Mixer'),
  ('MB04PN-R2-C', 'Round Pinless Tall Basin Mixer'),
  ('MB04PN-R2-CH', 'Round Pinless Tall Basin Mixer'),
  ('MB04PN-R2-PVDBB', 'Round Pinless Tall Basin Mixer'),
  ('MB04PN-R2-PVDBN', 'Round Pinless Tall Basin Mixer'),
  ('MB04PN-R2-PVDBZ', 'Round Pinless Tall Basin Mixer'),
  ('MB04PN-R2-PVDGM', 'Round Pinless Tall Basin Mixer'),
  ('MB05', 'Square Freestanding Bath Mixer'),
  ('MB06', 'Round Freestanding Bath Spout'),
  ('MB06-C', 'Round Freestanding Bath Spout'),
  ('MB06-CH', 'Round Freestanding Bath Spout'),
  ('MB06-PVDBB', 'Round Freestanding Bath Spout'),
  ('MB06-PVDBN', 'Round Freestanding Bath Spout')
ON CONFLICT (sku_code) DO UPDATE SET sku_name = EXCLUDED.sku_name;

INSERT INTO products (sku_code, sku_name) VALUES
  ('MB06-PVDBZ', 'Round Freestanding Bath Spout'),
  ('MB06-PVDGM', 'Round Freestanding Bath Spout'),
  ('MB08', 'Square Freestanding Bath Spout and Hand Shower'),
  ('MB08-C', 'Square Freestanding Bath Spout and Hand Shower'),
  ('MB09', 'Round Freestanding Bath Spout and Hand Shower'),
  ('MB09-C', 'Round Freestanding Bath Spout and Hand Shower'),
  ('MB09-CH', 'Round Freestanding Bath Spout and Hand Shower'),
  ('MB09-H', 'MB09 Handle'),
  ('MB09-PVDBB', 'Round Freestanding Bath Spout and Hand Shower'),
  ('MB09-PVDBN', 'Round Freestanding Bath Spout and Hand Shower'),
  ('MB09-PVDBZ', 'Round Freestanding Bath Spout and Hand Shower'),
  ('MB09-PVDGM', 'Round Freestanding Bath Spout and Hand Shower'),
  ('MB09PD', 'Round Paddle Freestanding Bath Spout and Hand Shower'),
  ('MB09PD-C', 'Round Paddle Freestanding Bath Spout and Hand Shower'),
  ('MB09PD-CH', 'Round Paddle Freestanding Bath Spout and Hand Shower'),
  ('MB09PD-PVDBB', 'Round Paddle Freestanding Bath Spout and Hand Shower'),
  ('MB09PD-PVDBN', 'Round Paddle Freestanding Bath Spout and Hand Shower'),
  ('MB09PD-PVDBZ', 'Round Paddle Freestanding Bath Spout and Hand Shower'),
  ('MB09PD-PVDGM', 'Round Paddle Freestanding Bath Spout and Hand Shower'),
  ('MB09PN', 'Round Pinless Freestanding Bath Spout and Hand Shower'),
  ('MB09PN-C', 'Round Pinless Freestanding Bath Spout and Hand Shower'),
  ('MB09PN-CH', 'Round Pinless Freestanding Bath Spout and Hand Shower'),
  ('MB09PN-PVDBB', 'Round Pinless Freestanding Bath Spout and Hand Shower'),
  ('MB09PN-PVDBN', 'Round Pinless Freestanding Bath Spout and Hand Shower'),
  ('MB09PN-PVDBZ', 'Round Pinless Freestanding Bath Spout and Hand Shower'),
  ('MB09PN-PVDGM', 'Round Pinless Freestanding Bath Spout and Hand Shower'),
  ('MB10', 'Round Three Piece Basin Tap'),
  ('MB10-C', 'Round Three Piece Basin Tap'),
  ('MB17', 'Round Gooseneck Basin Mixer with Cold Start'),
  ('MB17-C', 'Round Gooseneck Basin Mixer with Cold Start'),
  ('MB17-CH', 'Round Gooseneck Basin Mixer with Cold Start'),
  ('MB17-PVDBB', 'Round Gooseneck Basin Mixer with Cold Start'),
  ('MB17-PVDBN', 'Round Gooseneck Basin Mixer with Cold Start'),
  ('MB17-PVDBZ', 'Round Gooseneck Basin Mixer with Cold Start'),
  ('MB17-PVDGM', 'Round Gooseneck Basin Mixer with Cold Start'),
  ('MBRP-380110-PVDBB', 'Steel Round Bathroom Basin 380 x 110'),
  ('MBRP-380110-PVDBN', 'Steel Round Bathroom Basin 380 x 110'),
  ('MBRP-380110-PVDCH', 'Steel Round Bathroom Basin 380 x 110'),
  ('MBRP-380110-PVDGM', 'Steel Round Bathroom Basin 380 x 110'),
  ('MBRP-380110B-PVDBB', ''),
  ('MBRP-380110B-PVDBN', ''),
  ('MBRP-380110B-PVDCH', ''),
  ('MBRP-380110B-PVDGM', ''),
  ('MC05-PVDBN', 'Round Wall Combination Mixer and Curved Spout'),
  ('MCBL-01', 'Chopping Board'),
  ('MCO-01-GM', 'Kitchen Sink Colander'),
  ('MCO-01-NK', 'Kitchen Sink Colander'),
  ('MCO-01-PVDBB', 'Kitchen Sink Colander'),
  ('MCO-01-PVDBN', 'Kitchen Sink Colander'),
  ('MCO-01-PVDGM', 'Kitchen Sink Colander')
ON CONFLICT (sku_code) DO UPDATE SET sku_name = EXCLUDED.sku_name;

INSERT INTO products (sku_code, sku_name) VALUES
  ('MD01-SET', 'Round Colour Sample Disc Set'),
  ('MD01-SET.01', 'Round Colour Sample Disc Set REFER MD01.01-SET'),
  ('MD01-SS316', 'Round Colour Sample Disc individually boxed'),
  ('MD01.01-SET', 'Round Colour Sample Disc Set'),
  ('MD01.02-SET', 'Round Colour Sample Disc Set'),
  ('MD02-PVDBB', 'Sample Disc for Sinks Individually Boxed'),
  ('MD02-PVDGM', 'Sample Disc for Sinks Individually Boxed'),
  ('MD02-SET', 'Sink Colour Sample Pack'),
  ('MD03-PVDBB', 'Basin Sample Disc Individually Boxed'),
  ('MD03-PVDBN', 'Basin Sample Disc Individually Boxed'),
  ('MD03-PVDCH', 'Basin Sample Disc Individually Boxed'),
  ('MD03-PVDGM', 'Basin Sample Disc Individually Boxed'),
  ('MD03-SET', 'Sample Disc Set for Basins (4 x discs PVDBB, PVDBN, PVDCH, PVDGMS)'),
  ('MDR-01-GM', 'Dish Rack'),
  ('MDR-01-NK', 'Dish Rack'),
  ('MDR-01-PVDBB', 'Dish Rack'),
  ('MDR-01-PVDBN', 'Dish Rack'),
  ('MDR-01-PVDGM', 'Dish Rack'),
  ('MDS01', 'Square Door Stop'),
  ('MDS02', 'Round Door Stop'),
  ('MDS02-BB', 'Round Door Stop'),
  ('MDS02-C', 'Round Door Stop'),
  ('MDS02N', 'Round Door Stop'),
  ('MDS02N-C', 'Round Door Stop'),
  ('MDS02N-CH', 'Round Door Stop'),
  ('MDS02N-PVDBB', 'Round Door Stop'),
  ('MDS02N-PVDBN', 'Round Door Stop'),
  ('MDS02N-PVDBZ', 'Round Door Stop'),
  ('MDS02N-PVDGM', 'Round Door Stop'),
  ('MDS03', 'Round Half Moon Door Stop'),
  ('MDS03-BB', ''),
  ('MDS03-C', 'Round Half Moon Door Stop'),
  ('MGA01N', 'Glass to Glass Shower Door Hinge'),
  ('MGA01N-C', 'Glass to Glass Shower Door Hinge'),
  ('MGA01N-CH', 'Glass to Glass Shower Door Hinge'),
  ('MGA01N-PVDBB', 'Glass to Glass Shower Door Hinge'),
  ('MGA01N-PVDBN', 'Glass to Glass Shower Door Hinge'),
  ('MGA01N-PVDBZ', 'Glass to Glass Shower Door Hinge'),
  ('MGA01N-PVDGM', 'Glass to Glass Shower Door Hinge'),
  ('MGA02N', 'Glass to Wall Shower Door Hinge'),
  ('MGA02N-C', 'Glass to Wall Shower Door Hinge'),
  ('MGA02N-CH', 'Glass to Wall Shower Door Hinge'),
  ('MGA02N-PVDBB', 'Glass to Wall Shower Door Hinge'),
  ('MGA02N-PVDBN', 'Glass to Wall Shower Door Hinge'),
  ('MGA02N-PVDBZ', 'Glass to Wall Shower Door Hinge'),
  ('MGA02N-PVDGM', 'Glass to Wall Shower Door Hinge'),
  ('MGA03N', 'Glass Fixing U Bracket'),
  ('MGA03N-C', 'Glass Fixing U Bracket'),
  ('MGA03N-CH', 'Glass Fixing U Bracket'),
  ('MGA03N-PVDBB', 'Glass Fixing U Bracket')
ON CONFLICT (sku_code) DO UPDATE SET sku_name = EXCLUDED.sku_name;

INSERT INTO products (sku_code, sku_name) VALUES
  ('MGA03N-PVDBN', 'Glass Fixing U Bracket'),
  ('MGA03N-PVDBZ', 'Glass Fixing U Bracket'),
  ('MGA03N-PVDGM', 'Glass Fixing U Bracket'),
  ('MGA04N', 'Shower Door Round Handle'),
  ('MGA04N-C', 'Shower Door Round Handle'),
  ('MGA04N-CH', 'Shower Door Round Handle'),
  ('MGA04N-PVDBB', 'Shower Door Round Handle'),
  ('MGA04N-PVDBN', 'Shower Door Round Handle'),
  ('MGA04N-PVDBZ', 'Shower Door Round Handle'),
  ('MGA04N-PVDGM', 'Shower Door Round Handle'),
  ('MH04N', 'Round Shower Rose 200mm'),
  ('MH04N-C', 'Round Shower Rose 200mm'),
  ('MH04N-CH', 'Round Shower Rose 200mm'),
  ('MH04N-PVDBB', 'Round Shower Rose 200mm'),
  ('MH04N-PVDBN', 'Round Shower Rose 200mm'),
  ('MH04N-PVDBZ', 'Round Shower Rose 200mm'),
  ('MH04N-PVDGM', 'Round Shower Rose 200mm'),
  ('MH06N', 'Round Shower Rose 300mm'),
  ('MH06N-C', 'Round Shower Rose 300mm'),
  ('MH06N-CH', 'Round Shower Rose 300mm'),
  ('MH06N-PVDBB', 'Round Shower Rose 300mm'),
  ('MH06N-PVDBN', 'Round Shower Rose 300mm'),
  ('MH06N-PVDBZ', 'Round Shower Rose 300mm'),
  ('MH06N-PVDGM', 'Round Shower Rose 300mm'),
  ('MH14N-SS316', 'Outdoor Round Shower Rose 200mm SS316'),
  ('MHB01N', 'Hand Bidet with Hand Piece, Bracket & Hose'),
  ('MHB01N-C', 'Hand Bidet with Hand Piece, Bracket & Hose'),
  ('MHB01N-CH', 'Hand Bidet with Hand Piece, Bracket & Hose'),
  ('MHB01N-PVDBB', 'Hand Bidet with Hand Piece, Bracket & Hose'),
  ('MHB01N-PVDBN', 'Hand Bidet with Hand Piece, Bracket & Hose'),
  ('MHB01N-PVDBZ', 'Hand Bidet with Hand Piece, Bracket & Hose'),
  ('MHB01N-PVDGM', 'Hand Bidet with Hand Piece, Bracket & Hose'),
  ('MHT02B-C', 'Heated Vertical Towel Rail'),
  ('MHT02B-CH', 'Heated Vertical Towel Rail'),
  ('MHT02B-PVDBB', 'Heated Vertical Towel Rail'),
  ('MHT02B-PVDBN', 'Heated Vertical Towel Rail'),
  ('MHT02B-PVDBZ', 'Heated Vertical Towel Rail'),
  ('MHT02B-PVDGM', 'Heated Vertical Towel Rail'),
  ('MK02-CH', 'Round Kitchen Mixer Tap'),
  ('MK02-PVDBB', 'Round Kitchen Mixer Tap'),
  ('MK02-PVDBN', 'Round Kitchen Mixer Tap'),
  ('MK02-PVDBZ', 'Round Kitchen Mixer Tap'),
  ('MK02-PVDGM', 'Round Kitchen Mixer Tap'),
  ('MK03', 'Round Gooseneck Kitchen Mixer Tap'),
  ('MK03-C', 'Round Gooseneck Kitchen Mixer Tap'),
  ('MK03-CH', 'Round Gooseneck Kitchen Mixer Tap'),
  ('MK03-PVDBB', 'Round Gooseneck Kitchen Mixer Tap'),
  ('MK03-PVDBN', 'Round Gooseneck Kitchen Mixer Tap'),
  ('MK03-PVDBZ', 'Round Gooseneck Kitchen Mixer Tap'),
  ('MK03-PVDCH', 'Round Gooseneck Kitchen Mixer Tap')
ON CONFLICT (sku_code) DO UPDATE SET sku_name = EXCLUDED.sku_name;

INSERT INTO products (sku_code, sku_name) VALUES
  ('MK03-PVDGM', 'Round Gooseneck Kitchen Mixer Tap'),
  ('MK03PD', 'Round Paddle Gooseneck Kitchen Mixer Tap'),
  ('MK03PD-C', 'Round Paddle Gooseneck Kitchen Mixer Tap'),
  ('MK03PD-CH', 'Round Paddle Gooseneck Kitchen Mixer Tap'),
  ('MK03PD-PVDBB', 'Round Paddle Gooseneck Kitchen Mixer Tap'),
  ('MK03PD-PVDBN', 'Round Paddle Gooseneck Kitchen Mixer Tap'),
  ('MK03PD-PVDBZ', 'Round Paddle Gooseneck Kitchen Mixer Tap'),
  ('MK03PD-PVDGM', 'Round Paddle Gooseneck Kitchen Mixer Tap'),
  ('MK03PN', 'Round Pinless Gooseneck Kitchen Mixer Tap'),
  ('MK03PN-C', 'Round Pinless Gooseneck Kitchen Mixer Tap'),
  ('MK03PN-CH', 'Round Pinless Gooseneck Kitchen Mixer Tap'),
  ('MK03PN-PVDBB', 'Round Pinless Gooseneck Kitchen Mixer Tap'),
  ('MK03PN-PVDBN', 'Round Pinless Gooseneck Kitchen Mixer Tap'),
  ('MK03PN-PVDBZ', 'Round Pinless Gooseneck Kitchen Mixer Tap'),
  ('MK03PN-PVDGM', 'Round Pinless Gooseneck Kitchen Mixer Tap'),
  ('MK10N-SS316', 'Outdoor Kitchen Mixer SS316'),
  ('MK17', 'Piccola Out Kitchen Mixer Tap'),
  ('MK17-C', 'Piccola Out Kitchen Mixer Tap'),
  ('MK17-CH', 'Piccola Out Kitchen Mixer Tap'),
  ('MK17-H', 'Handle for the MK17 and MB17'),
  ('MK17-H-C', 'Handle for the MK17 and MB17'),
  ('MK17-H-CH', 'Handle for the MK17 and MB17'),
  ('MK17-H-PVDBB', 'Handle for the MK17 and MB17 PVDBB'),
  ('MK17-H-PVDBN', 'Handle for the MK17 and MB17 PVDBN'),
  ('MK17-H-PVDGM', 'Handle for the MK17 and MB17 PVDGM'),
  ('MK17-PVDBB', 'Piccola Out Kitchen Mixer Tap'),
  ('MK17-PVDBN', 'Piccola Out Kitchen Mixer Tap'),
  ('MK17-PVDBZ', 'Piccola Out Kitchen Mixer Tap'),
  ('MK17-PVDGM', 'Piccola Out Kitchen Mixer Tap'),
  ('MK17PD', 'Round Paddle Piccola Pull Out Kitchen Mixer Tap'),
  ('MK17PD-C', 'Round Paddle Piccola Pull Out Kitchen Mixer Tap'),
  ('MK17PD-CH', 'Round Paddle Piccola Pull Out Kitchen Mixer Tap'),
  ('MK17PD-PVDBB', 'Round Paddle Piccola Pull Out Kitchen Mixer Tap'),
  ('MK17PD-PVDBN', 'Round Paddle Piccola Pull Out Kitchen Mixer Tap'),
  ('MK17PD-PVDBZ', 'Round Paddle Piccola Pull Out Kitchen Mixer Tap'),
  ('MK17PD-PVDGM', 'Round Paddle Piccola Pull Out Kitchen Mixer Tap'),
  ('MK17PN', 'Round Pinless Piccola Pull Out Kitchen Mixer Tap'),
  ('MK17PN-C', 'Round Pinless Piccola Pull Out Kitchen Mixer Tap'),
  ('MK17PN-CH', 'Round Pinless Piccola Pull Out Kitchen Mixer Tap'),
  ('MK17PN-PVDBB', 'Round Pinless Piccola Pull Out Kitchen Mixer Tap'),
  ('MK17PN-PVDBN', 'Round Pinless Piccola Pull Out Kitchen Mixer Tap'),
  ('MK17PN-PVDBZ', 'Round Pinless Piccola Pull Out Kitchen Mixer Tap'),
  ('MK17PN-PVDGM', 'Round Pinless Piccola Pull Out Kitchen Mixer Tap'),
  ('MKS-D1160440D-SS', 'Drainboard Double Bowl'),
  ('MKS-D670440-SS', 'undermount double bowl (no overflow hole)'),
  ('MKS-D760440-SS', 'undermount double bowl (no overflow hole)'),
  ('MKS-D7644DR-SS', 'Kitchen Sink Double Bowl 760*440 (specific project)'),
  ('MKS-D860440-SS', 'undermount double bowl (no overflow hole)'),
  ('MKS-S300450-SS', 'Kitchen Sink Single Bowl 300 x 450'),
  ('MKS-S322222-SS', 'undermount single bowl (no overflow hole)')
ON CONFLICT (sku_code) DO UPDATE SET sku_name = EXCLUDED.sku_name;

INSERT INTO products (sku_code, sku_name) VALUES
  ('MKS-S380440-SS', 'undermount single bowl (no overflow hole)'),
  ('MKS-S3844SR-SS', 'Kitchen Sink Single Bowl 380*440'),
  ('MKS-S440440-SS', 'Kitchen Sink Single Bowl 440 x 440 304'),
  ('MKS-S440440-SS316', 'Outdoor Sink SS316'),
  ('MKS-S450450-SS', 'undermount single bowl (no overflow hole)'),
  ('MKS-S550450-SS', 'Kitchen Sink Single Bowl 550 x 450'),
  ('MKS-S760440-SS', 'undermount Single bowl (no overflow hole)'),
  ('MKS-S840440D-SS', 'Drainboard Single Bowl'),
  ('MKSP-D1160440D-GM', 'Kitchen Sink Double Bowl & Drainboard 1160 x 440'),
  ('MKSP-D1160440D-NK', 'Kitchen Sink Double Bowl & Drainboard 1160 x 440'),
  ('MKSP-D1160440D-PVDBB', 'Kitchen Sink Double Bowl & Drainboard 1160 x 440'),
  ('MKSP-D1160440D-PVDBN', 'Kitchen Sink Double Bowl & Drainboard 1160 x 440'),
  ('MKSP-D1160440D-PVDGM', 'Kitchen Sink Double Bowl & Drainboard 1160 x 440'),
  ('MKSP-D670440-GM', 'Kitchen Sink One & Half Bowl'),
  ('MKSP-D670440-NK', 'Kitchen Sink One & Half Bowl 670 x 440'),
  ('MKSP-D670440-PVDBB', 'Kitchen Sink One & Half Bowl 670 x 440'),
  ('MKSP-D670440-PVDBN', 'Kitchen Sink One & Half Bowl 670 x 440'),
  ('MKSP-D670440-PVDGM', 'Kitchen Sink One & Half Bowl 670 x 440'),
  ('MKSP-D760440-GM', 'Kitchen Sink Double Bowl 760 x 440'),
  ('MKSP-D760440-NK', 'Kitchen Sink Double Bowl 760 x 440'),
  ('MKSP-D760440-PVDBB', 'Kitchen Sink Double Bowl 760 x 440'),
  ('MKSP-D760440-PVDBN', 'Kitchen Sink Double Bowl 760 x 440'),
  ('MKSP-D760440-PVDGM', 'Kitchen Sink Double Bowl 760 x 440'),
  ('MKSP-D860440-GM', 'Kitchen Sink Double Bowl 860 x 440'),
  ('MKSP-D860440-NK', 'Kitchen Sink Double Bowl 860 x 440'),
  ('MKSP-D860440-PVDBB', 'Kitchen Sink Double Bowl 860 x 440'),
  ('MKSP-D860440-PVDBN', 'Kitchen Sink Double Bowl 860 x 440'),
  ('MKSP-D860440-PVDGM', 'Kitchen Sink Double Bowl 860 x 440'),
  ('MKSP-S322222-GM', 'Bar Sink Single Bowl 382 x 272 Brushed'),
  ('MKSP-S322222-NK', 'Bar Sink Single Bowl 382 x 272'),
  ('MKSP-S322222-PVDBB', 'Bar Sink Single Bowl 382 x 272'),
  ('MKSP-S322222-PVDBN', 'Bar Sink Single Bowl 382 x 272'),
  ('MKSP-S322222-PVDGM', 'Bar Sink Single Bowl 382 x 272'),
  ('MKSP-S380440-GM', 'Kitchen Sink Single Bowl 380 x 440'),
  ('MKSP-S380440-NK', 'Kitchen Sink Single Bowl 380 x 440'),
  ('MKSP-S380440-PVDBB', 'Kitchen Sink Single Bowl 380 x 440'),
  ('MKSP-S380440-PVDBN', 'Kitchen Sink Single Bowl 380 x 440'),
  ('MKSP-S380440-PVDGM', 'Kitchen Sink Single Bowl 380 x 440'),
  ('MKSP-S450450-GM', 'Kitchen Sink Single Bowl 450 x 450'),
  ('MKSP-S450450-NK', 'Kitchen Sink Single Bowl 450 x 450'),
  ('MKSP-S450450-PVDBB', 'Kitchen Sink Single Bowl 450 x 450'),
  ('MKSP-S450450-PVDBN', 'Kitchen Sink Single Bowl 450 x 450'),
  ('MKSP-S450450-PVDGM', 'Kitchen Sink Single Bowl 450 x 450'),
  ('MKSP-S450450X-PVDBB', ''),
  ('MKSP-S450450X-PVDBN', ''),
  ('MKSP-S450450X-PVDGM', ''),
  ('MKSP-S760440-GM', 'Kitchen Sink Single Bowl 760 x 440'),
  ('MKSP-S760440-NK', 'Kitchen Sink Single Bowl 760 x 440'),
  ('MKSP-S760440-PVDBB', 'Kitchen Sink Single Bowl 760 x 440'),
  ('MKSP-S760440-PVDBN', 'Kitchen Sink Single Bowl 760 x 440')
ON CONFLICT (sku_code) DO UPDATE SET sku_name = EXCLUDED.sku_name;

INSERT INTO products (sku_code, sku_name) VALUES
  ('MKSP-S760440-PVDGM', 'Kitchen Sink Single Bowl 760 x 440'),
  ('MKSP-S840440D-GM', 'Kitchen Sink Single Bowl & Drainboard 840 x 440'),
  ('MKSP-S840440D-NK', 'Kitchen Sink Single Bowl & Drainboard 840 x 440'),
  ('MKSP-S840440D-PVDBB', 'Kitchen Sink Single Bowl & Drainboard 840 x 440'),
  ('MKSP-S840440DX-PVDBB', ''),
  ('MKSP-S840440DX-PVDBN', ''),
  ('MKSP-S840440DX-PVDGM', ''),
  ('MP01', 'Square Hand Shower Single Function'),
  ('MP01-R', 'Round Hand Shower Single Function'),
  ('MP01-R-BB', 'Round Hand Shower Single Function'),
  ('MP01-R-C', 'Round Hand Shower Single Function'),
  ('MP01-R-CH', 'Round Hand Shower Single Function'),
  ('MP01-R-PVDBB', 'Round Hand Shower Single Function'),
  ('MP01-R-PVDBN', 'Round Hand Shower Single Function'),
  ('MP01-R-PVDBZ', 'Round Hand Shower Single Function'),
  ('MP01-R-PVDGM', 'Round Hand Shower Single Function'),
  ('MP01H-B', 'Round Hand Shower Three-Function'),
  ('MP01H-B-C', 'Round Hand Shower Three-Function'),
  ('MP01H-B-CH', 'Round Hand Shower Three-Function'),
  ('MP01H-B-PVDBB', 'Round Hand Shower Three-Function'),
  ('MP01H-B-PVDBN', 'Round Hand Shower Three-Function'),
  ('MP01H-B-PVDBZ', 'Round Hand Shower Three-Function'),
  ('MP01H-B-PVDGM', 'Round Hand Shower Three-Function'),
  ('MP01N-R-SS316', 'Round Hand Shower Single Function'),
  ('MP01S-B', 'Round Hand Shower Three-Function'),
  ('MP01S-B-C', 'Round Hand Shower Three-Function'),
  ('MP01S-B-CH', 'Round Hand Shower Three-Function'),
  ('MP01S-B-PVDBB', 'Round Hand Shower Three-Function'),
  ('MP01S-B-PVDBN', 'Round Hand Shower Three-Function'),
  ('MP01S-B-PVDBZ', 'Round Hand Shower Three-Function'),
  ('MP01S-B-PVDGM', 'Round Hand Shower Three-Function'),
  ('MP02-BR', 'Metal Shower Hose'),
  ('MP02-BR-BB', 'Metal Shower Hose Gold Gold'),
  ('MP02-BR-C', 'Metal Shower Hose'),
  ('MP02-BR-CH', 'Metal Shower Hose'),
  ('MP02-BR-PVDBB', 'Metal Shower Hose Gold'),
  ('MP02-BR-PVDBN', 'MP02-BR-PVDBN Braided hose'),
  ('MP02-BR-PVDBZ', 'Braided hose'),
  ('MP02-BR-PVDGM', 'Braided hose'),
  ('MP02-P', 'PVC shower hose'),
  ('MP02-P-C', 'PVC shower hose'),
  ('MP02N-BR-SS316', 'Braided hose'),
  ('MP03', 'MZ0401 Matte Shower Elbow'),
  ('MP03-R-PVDBB', 'Shower Bracket Connection'),
  ('MP03-WASHER', 'MP03 Washer'),
  ('MP04F-UNI', 'Universal all-in-one Pop Up Waste Basin & Bath'),
  ('MP04F-UNI-C', 'Universal all-in-one Pop Up Waste Basin & Bath'),
  ('MP04F-UNI-CH', 'Universal all-in-one Pop Up Waste Basin & Bath'),
  ('MP04F-UNI-PVDBB', 'Universal all-in-one Pop Up Waste Basin & Bath'),
  ('MP04F-UNI-PVDBN', 'Universal all-in-one Pop Up Waste Basin & Bath')
ON CONFLICT (sku_code) DO UPDATE SET sku_name = EXCLUDED.sku_name;

INSERT INTO products (sku_code, sku_name) VALUES
  ('MP04F-UNI-PVDBZ', 'Universal all-in-one Pop Up Waste Basin & Bath'),
  ('MP04F-UNI-PVDGM', 'Universal all-in-one Pop Up Waste Basin & Bath'),
  ('MP05F-R32', 'Round bottle trap for 32mm basin waste and 32mm waste pipe with 40mm adapter'),
  ('MP05F-R32-C', 'Round bottle trap for 32mm basin waste and 32mm waste pipe with 40mm adapter'),
  ('MP05F-R32-CH', 'Round bottle trap for 32mm basin waste and 32mm waste pipe with 40mm adapter'),
  ('MP05F-R32-PVDBB', 'Round bottle trap for 32mm basin waste and 32mm waste pipe with 40mm adapter'),
  ('MP05F-R32-PVDBN', 'Round bottle trap for 32mm basin waste and 32mm waste pipe with 40mm adapter'),
  ('MP05F-R32-PVDBZ', 'Round bottle trap for 32mm basin waste and 32mm waste pipe with 40mm adapter'),
  ('MP05F-R32-PVDGM', 'Round bottle trap for 32mm basin waste and 32mm waste pipe with 40mm adapter'),
  ('MP06-100', 'Square Floor Grate Shower Drain 100mm outlet'),
  ('MP06-100-C', 'Square Floor Grate Shower Drain 100mm outlet'),
  ('MP06-100-CH', 'Square Floor Grate Shower Drain 100mm outlet'),
  ('MP06-100-PVDBB', 'Square Floor Grate Shower Drain 100mm outlet'),
  ('MP06-100-PVDBN', 'Square Floor Grate Shower Drain 100mm outlet'),
  ('MP06-100-PVDBZ', 'Square Floor Grate Shower Drain 100mm outlet'),
  ('MP06-100-PVDGM', 'Square Floor Grate Shower Drain 100mm outlet'),
  ('MP06-50', 'Square Floor Grate Shower Drain 50mm outlet'),
  ('MP06-50-C', 'Square Floor Grate Shower Drain 50mm outlet'),
  ('MP06-50-CH', 'Square Floor Grate Shower Drain 50mm outlet'),
  ('MP06-50-PVDBB', 'Square Floor Grate Shower Drain 50mm outlet'),
  ('MP06-50-PVDBN', 'Square Floor Grate Shower Drain 50mm outlet'),
  ('MP06-50-PVDBZ', 'Square Floor Grate Shower Drain 50mm outlet'),
  ('MP06-50-PVDGM', 'Square Floor Grate Shower Drain 50mm outlet'),
  ('MP06-80', 'Square Floor Grate Shower Drain 80mm outlet'),
  ('MP06-80-C', 'Square Floor Grate Shower Drain 80mm outlet'),
  ('MP06-80-CH', 'Square Floor Grate Shower Drain 80mm outlet'),
  ('MP06-80-PVDBB', 'Square Floor Grate Shower Drain 80mm outlet'),
  ('MP06-80-PVDBN', 'Square Floor Grate Shower Drain 80mm outlet'),
  ('MP06-80-PVDBZ', 'Square Floor Grate Shower Drain 80mm outlet'),
  ('MP06-80-PVDGM', 'Square Floor Grate Shower Drain 80mm outlet'),
  ('MP06N-T100-CH', 'Shower Waste with Tile Insert'),
  ('MP06N-T100-PVDBB', 'Shower Waste with Tile Insert'),
  ('MP06N-T100-PVDBN', 'Shower Waste with Tile Insert'),
  ('MP06N-T100-PVDBZ', 'Shower Waste with Tile Insert'),
  ('MP06N-T100-PVDGM', 'Shower Waste with Tile Insert'),
  ('MP09-CH', 'Round Soap Dispenser'),
  ('MP09-PVDBN', 'Round Soap Dispenser'),
  ('MP09-PVDGM', 'Round Soap Dispenser'),
  ('MP09-STRAW', 'Round Soap Dispenser Straw Only'),
  ('MP10N-SS316', 'Outdoor Soap Dispenser Bracket SS316'),
  ('MPWT01', 'Fitting for Spouts (needs 2 x 20mm screws) (Can also be used for Showers)'),
  ('MR01', 'Square Double Towel Rail 600mm'),
  ('MR01-C', 'Square Double Towel Rail 600mm'),
  ('MR01-PVDBN', 'Square Double Towel Rail 600mm'),
  ('MR01-R', 'Round Double Towel Rail 600mm'),
  ('MR01-R-C', 'Round Double Towel Rail 600mm'),
  ('MR01-R-CH', 'Round Double Towel Rail 600mm'),
  ('MR01-R-PVDBB', 'Round Double Towel Rail 600mm'),
  ('MR01-R-PVDBN', 'Round Double Towel Rail 600mm'),
  ('MR01-R-PVDBZ', 'Round Double Towel Rail 600mm')
ON CONFLICT (sku_code) DO UPDATE SET sku_name = EXCLUDED.sku_name;

INSERT INTO products (sku_code, sku_name) VALUES
  ('MR01-R-PVDGM', 'Round Double Towel Rail 600mm'),
  ('MR01-R90', 'Round Double Towel Rail 900mm'),
  ('MR01-R90-C', 'Round Double Towel Rail 900mm'),
  ('MR01-R90-CH', 'Round Double Towel Rail 900mm'),
  ('MR01-R90-PVDBB', 'Round Double Towel Rail 900mm'),
  ('MR01-R90-PVDBN', 'Round Double Towel Rail 900mm'),
  ('MR01-R90-PVDBZ', 'Round Double Towel Rail 900mm'),
  ('MR01-R90-PVDGM', 'Round Double Towel Rail 900mm'),
  ('MR01-S90', 'Square Single Towel Rail 900mm'),
  ('MR01-SR30', 'Round Single Towel Rail 300mm'),
  ('MR01-SR30-C', 'Single towel rail 300mm'),
  ('MR01-SR30-CH', 'Single towel rail 300mm'),
  ('MR01-SR30-PVDBB', 'Single towel rail 300mm'),
  ('MR01-SR30-PVDBN', 'Single towel rail 300mm'),
  ('MR01-SR30-PVDBZ', 'Single towel rail 300mm'),
  ('MR01-SR30-PVDGM', 'Single towel rail 300mm'),
  ('MR01-SR60', 'Round Single Towel Rail 600mm'),
  ('MR01-SR60-C', 'Round Single Towel Rail 600mm'),
  ('MR01-SR60-CH', 'Round Single Towel Rail 600mm'),
  ('MR01-SR60-PVDBB', 'Round Single Towel Rail 600mm'),
  ('MR01-SR60-PVDBN', 'Round Single Towel Rail 600mm'),
  ('MR01-SR60-PVDBZ', 'Round Single Towel Rail 600mm'),
  ('MR01-SR60-PVDGM', 'Round Single Towel Rail 600mm'),
  ('MR01-SR90', 'Round Single Towel Rail 900mm'),
  ('MR01-SR90-C', 'Round Single Towel Rail 900mm'),
  ('MR01-SR90-CH', 'Round Single Towel Rail 900mm'),
  ('MR01-SR90-PVDBB', 'Round Single Towel Rail 900mm'),
  ('MR01-SR90-PVDBN', 'Round Single Towel Rail 900mm'),
  ('MR01-SR90-PVDBZ', 'Round Single Towel Rail 900mm'),
  ('MR01-SR90-PVDGM', 'Round Single Towel Rail 900mm'),
  ('MR02-C', 'Square Toilet Roll Holder'),
  ('MR02-R', 'Round Toilet Roll Holder'),
  ('MR02-R-C', 'Round Toilet Roll Holder'),
  ('MR02-R-CH', 'Round Toilet Roll Holder'),
  ('MR02-R-PVDBB', 'Round Toilet Roll Holder'),
  ('MR02-R-PVDBN', 'Round Toilet Roll Holder'),
  ('MR02-R-PVDBZ', 'Round Toilet Roll Holder'),
  ('MR02-R-PVDGM', 'Round Toilet Roll Holder'),
  ('MR03', 'Square Robe Hook'),
  ('MR03-PVDBN', 'Square Robe Hook'),
  ('MR03-R', 'Round Robe Hook'),
  ('MR03-R-C', 'Round Robe Hook'),
  ('MR03-R-CH', 'Round Robe Hook'),
  ('MR03-R-PVDBB', 'Round Robe Hook'),
  ('MR03-R-PVDBN', 'Round Robe Hook'),
  ('MR03-R-PVDBZ', 'Round Robe Hook'),
  ('MR03-R-PVDGM', 'Round Robe Hook'),
  ('MR05', 'Square Guest Towel Rail'),
  ('MR05-C', 'Square Guest Towel Rail'),
  ('MR05-PVDBN', 'Square Guest Towel Rail')
ON CONFLICT (sku_code) DO UPDATE SET sku_name = EXCLUDED.sku_name;

INSERT INTO products (sku_code, sku_name) VALUES
  ('MR05-R', 'Round Guest Towel Rail'),
  ('MR05-R-C', 'Round Guest Towel Rail'),
  ('MR05-R-CH', 'Round Guest Towel Rail'),
  ('MR05-R-P-CH', 'Matte Guest Towel Rail Round Back Plate Only'),
  ('MR05-R-PVDBB', 'Round Guest Towel Rail'),
  ('MR05-R-PVDBN', 'Round Guest Towel Rail'),
  ('MR05-R-PVDBZ', 'Round Guest Towel Rail'),
  ('MR05-R-PVDGM', 'Round Guest Towel Rail'),
  ('MR09N-R-SS316', 'Outdoor Robe Hook SS316'),
  ('MRCH-1E07N-CH', 'Oppen Edge-Pull 75mm Cabinet Handle'),
  ('MRCH-1E07N-PVDBB', 'Oppen Edge-Pull 75mm Cabinet Handle'),
  ('MRCH-1E07N-PVDBN', 'Oppen Edge-Pull 75mm Cabinet Handle'),
  ('MRCH-1E07N-PVDBZ', 'Oppen Edge-Pull 75mm Cabinet Handle'),
  ('MRCH-1E07N-PVDGM', 'Oppen Edge-Pull 75mm Cabinet Handle'),
  ('MRCH-1E15N-CH', 'Oppen Edge-Pull 150mm Cabinet Handle'),
  ('MRCH-1E15N-PVDBB', 'Oppen Edge-Pull 150mm Cabinet Handle'),
  ('MRCH-1E15N-PVDBN', 'Oppen Edge-Pull 150mm Cabinet Handle'),
  ('MRCH-1E15N-PVDBZ', 'Oppen Edge-Pull 150mm Cabinet Handle'),
  ('MRCH-1E15N-PVDGM', 'Oppen Edge-Pull 150mm Cabinet Handle'),
  ('MRCH-1E30N-CH', 'Oppen Edge-Pull 300mm Cabinet Handle'),
  ('MRCH-1E30N-PVDBB', 'Oppen Edge-Pull 300mm Cabinet Handle'),
  ('MRCH-1E30N-PVDBN', 'Oppen Edge-Pull 300mm Cabinet Handle'),
  ('MRCH-1E30N-PVDBZ', 'Oppen Edge-Pull 300mm Cabinet Handle'),
  ('MRCH-1E30N-PVDGM', 'Oppen Edge-Pull 300mm Cabinet Handle'),
  ('MRCH-1K00N-CH', 'Oppen Knob Cabinet Handle (Brushed)'),
  ('MRCH-1K00N-PVDBB', 'Oppen Knob Cabinet Handle (Brushed)'),
  ('MRCH-1K00N-PVDBN', 'Oppen Knob Cabinet Handle (Brushed)'),
  ('MRCH-1K00N-PVDBZ', 'Oppen Knob Cabinet Handle (Brushed)'),
  ('MRCH-1K00N-PVDGM', 'Oppen Knob Cabinet Handle (Brushed)'),
  ('MRCH-1P20N-CH', 'Oppen Round Pull 200mm Cabinet Handle (Brushed)'),
  ('MRCH-1P20N-PVDBB', 'Oppen Round Pull 200mm Cabinet Handle (Brushed)'),
  ('MRCH-1P20N-PVDBN', 'Oppen Round Pull 200mm Cabinet Handle (Brushed)'),
  ('MRCH-1P20N-PVDBZ', 'Oppen Round Pull 200mm Cabinet Handle (Brushed)'),
  ('MRCH-1P20N-PVDGM', 'Oppen Round Pull 200mm Cabinet Handle (Brushed)'),
  ('MRCH-1P32N-CH', 'Oppen Round Pull 328mm Cabinet Handle (Brushed'),
  ('MRCH-1P32N-PVDBB', 'Oppen Round Pull 328mm Cabinet Handle (Brushed'),
  ('MRCH-1P32N-PVDBN', 'Oppen Round Pull 328mm Cabinet Handle (Brushed'),
  ('MRCH-1P32N-PVDBZ', 'Oppen Round Pull 328mm Cabinet Handle (Brushed'),
  ('MRCH-1P32N-PVDGM', 'Oppen Round Pull 328mm Cabinet Handle (Brushed'),
  ('MRCH-1P52N-CH', 'Oppen Round Pull 520mm Cabinet Handle (Brushed)'),
  ('MRCH-1P52N-PVDBB', 'Oppen Round Pull 520mm Cabinet Handle (Brushed)'),
  ('MRCH-1P52N-PVDBN', 'Oppen Round Pull 520mm Cabinet Handle (Brushed)'),
  ('MRCH-1P52N-PVDBZ', 'Oppen Round Pull 520mm Cabinet Handle (Brushed)'),
  ('MRCH-1P52N-PVDGM', 'Oppen Round Pull 520mm Cabinet Handle (Brushed)'),
  ('MRCH-1T00N-CH', 'Oppen T-Pull Cabinet Handle'),
  ('MRCH-1T00N-PVDBB', 'Oppen T-Pull Cabinet Handle'),
  ('MRCH-1T00N-PVDBN', 'Oppen T-Pull Cabinet Handle'),
  ('MRCH-1T00N-PVDBZ', 'Oppen T-Pull Cabinet Handle'),
  ('MRCH-1T00N-PVDGM', 'Oppen T-Pull Cabinet Handle'),
  ('MRCH-2P20N-CH', 'Oppen Round Pull 200mm Cabinet Handle (Linear)')
ON CONFLICT (sku_code) DO UPDATE SET sku_name = EXCLUDED.sku_name;

INSERT INTO products (sku_code, sku_name) VALUES
  ('MRCH-2P20N-PVDBB', 'Oppen Round Pull 200mm Cabinet Handle (Linear)'),
  ('MRCH-2P20N-PVDBN', 'Oppen Round Pull 200mm Cabinet Handle (Linear)'),
  ('MRCH-2P20N-PVDBZ', 'Oppen Round Pull 200mm Cabinet Handle (Linear)'),
  ('MRCH-2P20N-PVDGM', 'Oppen Round Pull 200mm Cabinet Handle (Linear)'),
  ('MRCH-2P32N-CH', 'Oppen Round Pull 328mm Cabinet Handle (Linear)'),
  ('MRCH-2P32N-PVDBB', 'Oppen Round Pull 328mm Cabinet Handle (Linear)'),
  ('MRCH-2P32N-PVDBN', 'Oppen Round Pull 328mm Cabinet Handle (Linear)'),
  ('MRCH-2P32N-PVDBZ', 'Oppen Round Pull 328mm Cabinet Handle (Linear)'),
  ('MRCH-2P32N-PVDGM', 'Oppen Round Pull 328mm Cabinet Handle (Linear)'),
  ('MRCH-2P52N-CH', 'Oppen Round Pull 520mm Cabinet Handle (Linear)'),
  ('MRCH-2P52N-PVDBB', 'Oppen Round Pull 520mm Cabinet Handle (Linear)'),
  ('MRCH-2P52N-PVDBN', 'Oppen Round Pull 520mm Cabinet Handle (Linear)'),
  ('MRCH-2P52N-PVDBZ', 'Oppen Round Pull 520mm Cabinet Handle (Linear)'),
  ('MRCH-2P52N-PVDGM', 'Oppen Round Pull 520mm Cabinet Handle (Linear)'),
  ('MRCH-2T00N-CH', 'Oppen T-Pull Cabinet Handle (Brushed)'),
  ('MRCH-2T00N-PVDBB', 'Oppen T-Pull Cabinet Handle (Brushed)'),
  ('MRCH-2T00N-PVDBN', 'Oppen T-Pull Cabinet Handle (Brushed)'),
  ('MRCH-2T00N-PVDBZ', 'Oppen T-Pull Cabinet Handle (Brushed)'),
  ('MRCH-2T00N-PVDGM', 'Oppen T-Pull Cabinet Handle (Brushed)'),
  ('MRCH-3T00N-CH', 'Oppen T-Pull Cabinet Handle (Linear)'),
  ('MRCH-3T00N-PVDBB', 'Oppen T-Pull Cabinet Handle (Linear)'),
  ('MRCH-3T00N-PVDBN', 'Oppen T-Pull Cabinet Handle (Linear)'),
  ('MRCH-3T00N-PVDBZ', 'Oppen T-Pull Cabinet Handle (Linear)'),
  ('MRCH-3T00N-PVDGM', 'Oppen T-Pull Cabinet Handle (Linear)'),
  ('MRRH-2D00N', 'Curvae Double Robe Hook'),
  ('MRRH-2D00N-C', 'Curvae Double Robe Hook'),
  ('MRRH-2D00N-CH', 'Curvae Double Robe Hook'),
  ('MRRH-2D00N-PVDBB', 'Curvae Double Robe Hook'),
  ('MRRH-2D00N-PVDBN', 'Curvae Double Robe Hook'),
  ('MRRH-2D00N-PVDBZ', 'Curvae Double Robe Hook'),
  ('MRRH-2D00N-PVDGM', 'Curvae Double Robe Hook'),
  ('MRRH-2S00N', 'Curvae Single Robe Hook'),
  ('MRRH-2S00N-C', 'Curvae Single Robe Hook'),
  ('MRRH-2S00N-CH', 'Curvae Single Robe Hook'),
  ('MRRH-2S00N-PVDBB', 'Curvae Single Robe Hook'),
  ('MRRH-2S00N-PVDBN', 'Curvae Single Robe Hook'),
  ('MRRH-2S00N-PVDBZ', 'Curvae Single Robe Hook'),
  ('MRRH-2S00N-PVDGM', 'Curvae Single Robe Hook'),
  ('MRSS-2040N', 'Curvae Shower Shelf 400mm'),
  ('MRSS-2040N-C', 'Curvae Shower Shelf 400mm'),
  ('MRSS-2040N-CH', 'Curvae Shower Shelf 400mm'),
  ('MRSS-2040N-PVDBB', 'Curvae Shower Shelf 400mm'),
  ('MRSS-2040N-PVDBN', 'Curvae Shower Shelf 400mm'),
  ('MRSS-2040N-PVDBZ', 'Curvae Shower Shelf 400mm'),
  ('MRSS-2040N-PVDGM', 'Curvae Shower Shelf 400mm'),
  ('MRTP-3000N', 'Curvae Toilet Roll Holder'),
  ('MRTP-3000N-C', 'Curvae Toilet Roll Holder'),
  ('MRTP-3000N-CH', 'Curvae Toilet Roll Holder'),
  ('MRTP-3000N-PVDBB', 'Curvae Toilet Roll Holder'),
  ('MRTP-3000N-PVDBN', 'Curvae Toilet Roll Holder')
ON CONFLICT (sku_code) DO UPDATE SET sku_name = EXCLUDED.sku_name;

INSERT INTO products (sku_code, sku_name) VALUES
  ('MRTP-3000N-PVDBZ', 'Curvae Toilet Roll Holder'),
  ('MRTP-3000N-PVDGM', 'Curvae Toilet Roll Holder'),
  ('MRTR-3D60N', 'Curvae Double Towel Rail 600mm'),
  ('MRTR-3D60N-C', 'Curvae Double Towel Rail 600mm'),
  ('MRTR-3D60N-CH', 'Curvae Double Towel Rail 600mm'),
  ('MRTR-3D60N-PVDBB', 'Curvae Double Towel Rail 600mm'),
  ('MRTR-3D60N-PVDBN', 'Curvae Double Towel Rail 600mm'),
  ('MRTR-3D60N-PVDBZ', 'Curvae Double Towel Rail 600mm'),
  ('MRTR-3D60N-PVDGM', 'Curvae Double Towel Rail 600mm'),
  ('MRTR-3D80N', 'Curvae Double Towel Rail 800mm'),
  ('MRTR-3D80N-C', 'Curvae Double Towel Rail 800mm'),
  ('MRTR-3D80N-CH', 'Curvae Double Towel Rail 800mm'),
  ('MRTR-3D80N-PVDBB', 'Curvae Double Towel Rail 800mm'),
  ('MRTR-3D80N-PVDBN', 'Curvae Double Towel Rail 800mm'),
  ('MRTR-3D80N-PVDBZ', 'Curvae Double Towel Rail 800mm'),
  ('MRTR-3D80N-PVDGM', 'Curvae Double Towel Rail 800mm'),
  ('MRTR-3S30N', 'Curvae Single Towel Rail 300mm'),
  ('MRTR-3S30N-C', 'Curvae Single Towel Rail 300mm'),
  ('MRTR-3S30N-CH', 'Curvae Single Towel Rail 300mm'),
  ('MRTR-3S30N-PVDBB', 'Curvae Single Towel Rail 300mm'),
  ('MRTR-3S30N-PVDBN', 'Curvae Single Towel Rail 300mm'),
  ('MRTR-3S30N-PVDBZ', 'Curvae Single Towel Rail 300mm'),
  ('MRTR-3S30N-PVDGM', 'Curvae Single Towel Rail 300mm'),
  ('MRTR-3S60N', 'Curvae Single Towel Rail 600mm'),
  ('MRTR-3S60N-C', 'Curvae Single Towel Rail 600mm'),
  ('MRTR-3S60N-CH', 'Curvae Single Towel Rail 600mm'),
  ('MRTR-3S60N-PVDBB', 'Curvae Single Towel Rail 600mm'),
  ('MRTR-3S60N-PVDBN', 'Curvae Single Towel Rail 600mm'),
  ('MRTR-3S60N-PVDBZ', 'Curvae Single Towel Rail 600mm'),
  ('MRTR-3S60N-PVDGM', 'Curvae Single Towel Rail 600mm'),
  ('MS01', 'Square Wall Spout'),
  ('MS01-C', 'Square Wall Spout'),
  ('MS01-PVDBN', 'Square Wall Spout'),
  ('MS05', 'Universal Round Curved Spout'),
  ('MS05-130', 'Universal Round Curved Spout 130mm'),
  ('MS05-130-C', 'Universal Round Curved Spout 130mm'),
  ('MS05-130-CH', 'Universal Round Curved Spout 130mm'),
  ('MS05-130-PVDBB', 'Universal Round Curved Spout 130mm'),
  ('MS05-130-PVDBN', 'Universal Round Curved Spout 130mm'),
  ('MS05-130-PVDBZ', 'Universal Round Curved Spout 130mm'),
  ('MS05-130-PVDGM', 'Universal Round Curved Spout 130mm'),
  ('MS05-180-C', 'Round Curved Spout 180mm'),
  ('MS05-180-CH', 'Round Curved Spout 180mm'),
  ('MS05-300', 'Round Curved Spout 300mm'),
  ('MS05-300-CH', 'Round Curved Spout 300mm'),
  ('MS05-300-PVDBB', 'Round Curved Spout 300mm'),
  ('MS05-C', 'Universal Round Curved Spout'),
  ('MS05-CH', 'Universal Round Curved Spout'),
  ('MS05-PVDBB', 'Universal Round Curved Spout'),
  ('MS05-PVDBN', 'Universal Round Curved Spout')
ON CONFLICT (sku_code) DO UPDATE SET sku_name = EXCLUDED.sku_name;

INSERT INTO products (sku_code, sku_name) VALUES
  ('MS05-PVDBZ', 'Universal Round Curved Spout'),
  ('MS05-PVDGM', 'Universal Round Curved Spout'),
  ('MS07', 'Round High-Rise Swivel Wall Spout'),
  ('MS07-C', 'Round High-Rise Swivel Wall Spout'),
  ('MS07-CH', 'Round High-Rise Swivel Wall Spout'),
  ('MS07-PVDBB', 'Round High-Rise Swivel Wall Spout'),
  ('MS07-PVDBN', 'Round High-Rise Swivel Wall Spout'),
  ('MS07-PVDBZ', 'Round High-Rise Swivel Wall Spout'),
  ('MS07-PVDGM', 'Round High-Rise Swivel Wall Spout'),
  ('MS08', 'Round High-Rise Swivel Hob Spout'),
  ('MS08-C', 'Round High-Rise Swivel Hob Spout'),
  ('MS08-CH', 'Round High-Rise Swivel Hob Spout'),
  ('MS08-P', 'MS08 Backplate Part 14'),
  ('MS08-P-C', 'MS08 Backplate Part 14'),
  ('MS08-P-CH', 'MS08 Backplate Part 14'),
  ('MS08-P-PVDBB', 'MS08 Backplate Part 14'),
  ('MS08-P-PVDBN', 'MS08 Backplate Part 14'),
  ('MS08-P-PVDGM', 'MS08 Backplate Part 14'),
  ('MS08-PVDBB', 'Round High-Rise Swivel Hob Spout'),
  ('MS08-PVDBN', 'Round High-Rise Swivel Hob Spout'),
  ('MS08-PVDBZ', 'Round High-Rise Swivel Hob Spout'),
  ('MS08-PVDGM', 'Round High-Rise Swivel Hob Spout'),
  ('MS09', 'Square High-Rise Swivel Hob Spout'),
  ('MS11', 'Round Hob Mounted Swivel Spout'),
  ('MS11-C', 'Round Hob Mounted Swivel Spout'),
  ('MS11-CH', 'Round Hob Mounted Swivel Spout'),
  ('MS11-PVDBB', 'Round Hob Mounted Swivel Spout'),
  ('MS11-PVDBN', 'Round Hob Mounted Swivel Spout'),
  ('MS11-PVDBZ', 'Round Hob Mounted Swivel Spout'),
  ('MS11-PVDGM', 'Round Hob Mounted Swivel Spout'),
  ('MS12N-SS316', 'Outdoor Universal Round Curved Spout SS316'),
  ('MS16', 'Round Swivel Wall Spout'),
  ('MS16-C', 'Round Swivel Wall Spout'),
  ('MS16-CH', 'Round Swivel Wall Spout'),
  ('MS16-PVDBB', 'Round Swivel Wall Spout'),
  ('MS16-PVDBN', 'Round Swivel Wall Spout'),
  ('MS16-PVDBZ', 'Round Swivel Wall Spout'),
  ('MS16-PVDGM', 'Round Swivel Wall Spout'),
  ('MST01', 'Clear Display Stand (with no fittings) use bundle codes only'),
  ('MST04-GM', 'Sink Strainer and Waste Plug Basket with Stopper PVD Finish'),
  ('MST04-NK', 'Sink Strainer and Waste Plug Basket with Stopper PVD Finish'),
  ('MST04-PVDBB', 'Sink Strainer and Waste Plug Basket with Stopper'),
  ('MST04-PVDBN', 'Sink Strainer and Waste Plug Basket with Stopper'),
  ('MST04-PVDGM', 'Lavello Sink Strainer and Waste Plug Basket with Stopper'),
  ('MTO02N-R', 'Round Toilet Brush and Holder'),
  ('MTO02N-R-B-CH', 'Toilet brush holder back plates'),
  ('MTO02N-R-C', 'Round Toilet Brush and Holder'),
  ('MTO02N-R-CH', 'Round Toilet Brush and Holder'),
  ('MTO02N-R-PVDBB', 'Round Toilet Brush and Holder'),
  ('MTO02N-R-PVDBN', 'Round Toilet Brush and Holder')
ON CONFLICT (sku_code) DO UPDATE SET sku_name = EXCLUDED.sku_name;

INSERT INTO products (sku_code, sku_name) VALUES
  ('MTO02N-R-PVDBZ', 'Round Toilet Brush and Holder'),
  ('MTO02N-R-PVDGM', 'Round Toilet Brush and Holder'),
  ('MW03-FIN', 'Round Wall Mixer Finish Kit'),
  ('MW03-FIN Display Fittings', ''),
  ('MW03-FIN-C', 'Round Wall Mixer Finish Kit'),
  ('MW03-FIN-CH', 'Round Wall Mixer Finish Kit'),
  ('MW03-FIN-PVDBB', 'Round Wall Mixer Finish Kit'),
  ('MW03-FIN-PVDBN', 'Round Wall Mixer Finish Kit'),
  ('MW03-FIN-PVDBZ', 'Round Wall Mixer Finish Kit'),
  ('MW03-FIN-PVDGM', 'Round Wall Mixer Finish Kit'),
  ('MW03-H', 'MW03/7 Handle Only (original handle 65mm )'),
  ('MW03-H-BB', 'MW03/7 Handle Only (original handle 65mm)'),
  ('MW03-H-C', 'MW03/7 Handle Only (original handle 65mm)'),
  ('MW03-H-CH', 'MW03/7 Handle Only (original handle 65mm)'),
  ('MW03-H-PVDBN', 'MW03/7 Handle only (original handle 65mm)'),
  ('MW03-H2', 'MW03/MW07 Handle Only (Version 2, 75mm)'),
  ('MW03-H2-BB', 'MW03/MW03 Handle Only (Version 2, 75mm)'),
  ('MW03-H2-C', 'MW03/MW07 Handle Only (Version 2, 75mm)'),
  ('MW03-H2-CH', 'MW03/MW07 Handle Only (Version 2, 75mm)'),
  ('MW03-H3', 'MW03/MW07 Handle Only (Version 3, 65mm)'),
  ('MW03-H3-BB', 'MW03/MW07 Handle Only (Version 3, 65mm)'),
  ('MW03-H3-C', 'MW03/MW07 Handle Only (Version 3, 65mm)'),
  ('MW03-H3-CH', 'MW03/MW07 Handle Only (Version 3, 65mm)'),
  ('MW03-H3-PVDBB', 'MW03/MW07 Handle Only (Version 3, 65mm)'),
  ('MW03-H3-PVDBN', 'MW03/MW07 Handle Only (Version 3, 65mm)'),
  ('MW03-H3-PVDBZ', 'MW03/MW07 Handle Only (Version 3, 65mm)'),
  ('MW03-H3-PVDGM', 'MW03/MW07 Handle Only (Version 3, 65mm)'),
  ('MW03PD-FIN', 'Round Wall Mixer Paddle Handle Finish Kit'),
  ('MW03PD-FIN-C', 'Round Wall Mixer Paddle Handle Finish Kit'),
  ('MW03PD-FIN-CH', 'Round Wall Mixer Paddle Handle Finish Kit'),
  ('MW03PD-FIN-PVDBB', 'Round Wall Mixer Paddle Handle Finish Kit'),
  ('MW03PD-FIN-PVDBN', 'Round Wall Mixer Paddle Handle Finish Kit'),
  ('MW03PD-FIN-PVDBZ', 'Round Wall Mixer Paddle Handle Finish Kit'),
  ('MW03PD-FIN-PVDGM', 'Round Wall Mixer Paddle Handle Finish Kit'),
  ('MW03PN-FIN', 'Round Wall Mixer Pinless Handle Finish Kit'),
  ('MW03PN-FIN-C', 'Round Wall Mixer Pinless Handle Finish Kit'),
  ('MW03PN-FIN-CH', 'Round Wall Mixer Pinless Handle Finish Kit'),
  ('MW03PN-FIN-PVDBB', 'Round Wall Mixer Pinless Handle Finish Kit'),
  ('MW03PN-FIN-PVDBN', 'Round Wall Mixer Pinless Handle Finish Kit'),
  ('MW03PN-FIN-PVDBZ', 'Round Wall Mixer Pinless Handle Finish Kit'),
  ('MW03PN-FIN-PVDGM', 'Round Wall Mixer Pinless Handle Finish Kit'),
  ('MW03S-FIN', 'Round Wall Mixer Short Pin-lever Finish Kit'),
  ('MW03S-FIN-C', 'Round Wall Mixer Short Pin-lever Finish Kit'),
  ('MW03S-FIN-CH', 'Round Wall Mixer Short Pin-lever Finish Kit'),
  ('MW03S-FIN-PVDBB', 'Round Wall Mixer Short Pin-lever Finish Kit'),
  ('MW03S-FIN-PVDBN', 'Round Wall Mixer Short Pin-lever Finish Kit'),
  ('MW03S-FIN-PVDBZ', 'Round Wall Mixer Short Pin-lever Finish Kit'),
  ('MW03S-FIN-PVDGM', 'Round Wall Mixer Short Pin-lever Finish Kit'),
  ('MW06', 'Round Quarter Turn Wall Top Assemblies'),
  ('MW06-C', 'Round Quarter Turn Wall Top Assemblies')
ON CONFLICT (sku_code) DO UPDATE SET sku_name = EXCLUDED.sku_name;

INSERT INTO products (sku_code, sku_name) VALUES
  ('MW06-CH', 'Round Quarter Turn Wall Top Assemblies'),
  ('MW06-PVDBB', 'Round Quarter Turn Wall Top Assemblies'),
  ('MW06-PVDBN', 'Round Quarter Turn Wall Top Assemblies'),
  ('MW06-PVDBZ', 'Round Quarter Turn Wall Top Assemblies'),
  ('MW06-PVDGM', 'Round Quarter Turn Wall Top Assemblies'),
  ('MW07TS-FIN', 'Round Diverter Mixer Finish Kit'),
  ('MW07TS-FIN Display Fitting', 'MW07TS-FIN Display Fitting'),
  ('MW07TS-FIN-C', 'Round Diverter Mixer Finish Kit'),
  ('MW07TS-FIN-CH', 'Round Diverter Mixer Finish Kit'),
  ('MW07TS-FIN-PVDBB', 'Round Diverter Mixer Finish Kit'),
  ('MW07TS-FIN-PVDBN', 'Round Diverter Mixer Finish Kit'),
  ('MW07TS-FIN-PVDBZ', 'Round Diverter Mixer Finish Kit'),
  ('MW07TS-FIN-PVDGM', 'Round Diverter Mixer Finish Kit'),
  ('MW08JL', 'Cross Handle Jumper Valve Wall Top Assemblies'),
  ('MW08JL-C', 'Cross Handle Jumper Valve Wall Top Assemblies'),
  ('MW08JL-CH', 'Cross Handle Jumper Valve Wall Top Assemblies'),
  ('MW08JL-PVDBB', 'Cross Handle Jumper Valve Wall Top Assemblies'),
  ('MW08JL-PVDBN', 'Cross Handle Jumper Valve Wall Top Assemblies'),
  ('MW08JL-PVDBZ', 'Cross Handle Jumper Valve Wall Top Assemblies'),
  ('MW08JL-PVDGM', 'Cross Handle Jumper Valve Wall Top Assemblies'),
  ('MW11', 'Circular Wall Taps'),
  ('MW11-C', 'Circular Wall Taps'),
  ('MW11-CH', 'Circular Wall Taps'),
  ('MW11-PVDBB', 'Circular Wall Taps'),
  ('MW11-PVDBN', 'Circular Wall Taps'),
  ('MW11-PVDBZ', 'Circular Wall Taps'),
  ('MW11-PVDGM', 'Circular Wall Taps'),
  ('MW12', 'Round Deck Mounted Mixer'),
  ('MW12-C', 'Round Deck Mounted Mixer'),
  ('MW12-CH', 'Round Deck Mounted Mixer'),
  ('MW12-PVDBB', 'Round Deck Mounted Mixer'),
  ('MW12-PVDBN', 'Round Deck Mounted Mixer'),
  ('MW12-PVDBZ', 'Round Deck Mounted Mixer'),
  ('MW12-PVDGM', 'Round Deck Mounted Mixer'),
  ('MW16N-SS316', 'Outdoor Wall Mixer SS316'),
  ('MZ0402', 'Round Three Function Hand Shower on Rail Column'),
  ('MZ0402-C', 'Round Three Function Hand Shower on Rail Column'),
  ('MZ0402-CH', 'Round Three Function Hand Shower on Rail Column'),
  ('MZ0402-PVDBB', 'Round Three Function Hand Shower on Rail Column'),
  ('MZ0402-PVDBN', 'Round Three Function Hand Shower on Rail Column'),
  ('MZ0402-PVDBZ', 'Round Three Function Hand Shower on Rail Column'),
  ('MZ0402-PVDGM', 'Round Three Function Hand Shower on Rail Column'),
  ('MZ0402-R', 'Round Hand Shower on Rail Column'),
  ('MZ0402-R-C', 'Round Hand Shower on Rail Column'),
  ('MZ0402-R-CH', 'Round Hand Shower on Rail Column'),
  ('MZ0402-R-PVDBB', 'Round Hand Shower on Rail Column'),
  ('MZ0402-R-PVDBN', 'Round Hand Shower on Rail Column'),
  ('MZ0402-R-PVDBZ', 'Round Hand Shower on Rail Column'),
  ('MZ0402-R-PVDGM', 'Round Hand Shower on Rail Column'),
  ('MZ04B', 'MZ0402/MZ0402-R complete bracket and hose only excluding hand shower')
ON CONFLICT (sku_code) DO UPDATE SET sku_name = EXCLUDED.sku_name;

INSERT INTO products (sku_code, sku_name) VALUES
  ('MZ04B-C', 'MZ0402/MZ0402-R complete bracket and hose only excluding hand shower'),
  ('MZ04B-CH', 'MZ0402/MZ0402-R complete bracket and hose only excluding hand shower'),
  ('MZ04B-PVDBB', 'MZ0402/MZ0402-R complete bracket and hose only excluding hand shower'),
  ('MZ04B-PVDBN', 'MZ0402/MZ0402-R complete bracket and hose only excluding hand shower'),
  ('MZ04B-PVDBZ', 'MZ0402/MZ0402-R complete bracket and hose only excluding hand shower'),
  ('MZ04B-PVDGM', 'MZ0402/MZ0402-R complete bracket and hose only excluding hand shower'),
  ('MZ06', 'Round Hand Shower on Swivel Bracket'),
  ('MZ06-C', 'Round Hand Shower on Swivel Bracket'),
  ('MZ06-CH', 'Round Hand Shower on Swivel Bracket'),
  ('MZ06-PVDBB', 'Round Hand Shower on Swivel Bracket'),
  ('MZ06-PVDBN', 'Round Hand Shower on Swivel Bracket'),
  ('MZ06-PVDBZ', 'Round Hand Shower on Swivel Bracket'),
  ('MZ06-PVDGM', 'Round Hand Shower on Swivel Bracket'),
  ('MZ06-R', 'Round Hand Shower on Swivel Bracket'),
  ('MZ06-R-C', 'Round Hand Shower on Swivel Bracket'),
  ('MZ06-R-CH', 'Round Hand Shower on Swivel Bracket'),
  ('MZ06-R-PVC', 'Round Hand Shower on Swivel Bracket with PVC Hose'),
  ('MZ06-R-PVDBB', 'Round Hand Shower on Swivel Bracket'),
  ('MZ06-R-PVDBN', 'Round Hand Shower on Swivel Bracket'),
  ('MZ06-R-PVDBZ', 'Round Hand Shower on Swivel Bracket'),
  ('MZ06-R-PVDGM', 'Round Hand Shower on Swivel Bracket'),
  ('MZ06B', 'MZ06/MZ06-R complete bracket and hose only excluding the hand shower'),
  ('MZ06B-C', 'MZ06/MZ06-R complete bracket and hose only excluding the hand shower'),
  ('MZ06B-CH', 'MZ06/MZ06-R complete bracket and hose only excluding the hand shower'),
  ('MZ06B-PVDBB', 'MZ06/MZ06-R complete bracket and hose only excluding the hand shower'),
  ('MZ06B-PVDBN', 'MZ06/MZ06-R complete bracket and hose only excluding the hand shower'),
  ('MZ06B-PVDBZ', 'MZ06/MZ06-R complete bracket and hose only excluding the hand shower'),
  ('MZ06B-PVDGM', 'MZ06/MZ06-R complete bracket and hose only excluding the hand shower'),
  ('MZ0704', 'Round Combination Shower Rail, 200mm Rose, Three-Function Hand Shower'),
  ('MZ0704-C', 'Round Combination Shower Rail 200mm Rose, Three Function Hand Shower'),
  ('MZ0704-CH', 'Round Combination Shower Rail 200mm Rose, Three Function Hand Shower'),
  ('MZ0704-PVDBB', 'Round Combination Shower Rail 200mm Rose, Three Function Hand Shower'),
  ('MZ0704-PVDBN', 'Round Combination Shower Rail 200mm Rose, Three Function Hand Shower'),
  ('MZ0704-PVDBZ', 'Round Combination Shower Rail 200mm Rose, Three Function Hand Shower'),
  ('MZ0704-PVDGM', 'Round Combination Shower Rail 200mm Rose, Three Function Hand Shower'),
  ('MZ0704-R', 'Round Combination Shower Rail 200mm Rose, Single Function Hand Shower'),
  ('MZ0704-R-C', 'Round Combination Shower Rail 200mm Rose, Single Function Hand Shower'),
  ('MZ0704-R-CH', 'Round Combination Shower Rail 200mm Rose, Single Function Hand Shower'),
  ('MZ0704-R-PVDBB', 'Round Combination Shower Rail 200mm Rose, Single Function Hand Shower'),
  ('MZ0704-R-PVDBN', 'Round Combination Shower Rail 200mm Rose, Single Function Hand Shower'),
  ('MZ0704-R-PVDBZ', 'Round Combination Shower Rail 200mm Rose, Single Function Hand Shower'),
  ('MZ0704-R-PVDGM', 'Round Combination Shower Rail 200mm Rose, Single Function Hand Shower'),
  ('MZ0705-C', 'Round Combination Shower Rail, 250mm Rose, Three-Function Hand Shower'),
  ('MZ0705-R', 'Round Combination Shower Rail 250mm Rose, Single Function Hand Shower'),
  ('MZ0705-R-C', 'Round Combination Shower Rail, 250mm Rose, Single Function Hand Shower'),
  ('MZ0705-R-CH', 'Round Combination Shower Rail 250mm Rose, Single Function Hand Shower'),
  ('MZ0705-R-PVDBN', 'Round Combination Shower Rail, 250mm Rose, Single Function Hand Shower'),
  ('MZ0706', 'Round Combination Shower Rail 300mm Rose, Three Function Hand Shower'),
  ('MZ0706-C', 'Round Combination Shower Rail 300mm Rose, Three Function Hand Shower'),
  ('MZ0706-CH', 'Round Combination Shower Rail 300mm Rose, Three Function Hand Shower')
ON CONFLICT (sku_code) DO UPDATE SET sku_name = EXCLUDED.sku_name;

INSERT INTO products (sku_code, sku_name) VALUES
  ('MZ0706-PVDBB', 'Round Combination Shower Rail 300mm Rose, Three Function Hand Shower'),
  ('MZ0706-PVDBN', 'Round Combination Shower Rail 300mm Rose, Three Function Hand Shower'),
  ('MZ0706-PVDBZ', 'Round Combination Shower Rail, 300mm Rose, Three Function Hand Shower'),
  ('MZ0706-PVDGM', 'Round Combination Shower Rail 300mm Rose, Three Function Hand Shower'),
  ('MZ0706-R', 'Round Combination Shower Rail 300mm Rose, Single Function Hand Shower'),
  ('MZ0706-R-C', 'Round Combination Shower Rail 300mm Rose, Single Function Hand Shower'),
  ('MZ0706-R-CH', 'Round Combination Shower Rail 300mm Rose, Single Function Hand Shower'),
  ('MZ0706-R-PVDBB', 'Round Combination Shower Rail, 300mm Rose, Single Function Hand Shower'),
  ('MZ0706-R-PVDBN', 'Round Combination Shower Rail, 300mm Rose, Single Function Hand Shower'),
  ('MZ0706-R-PVDBZ', 'Round Combination Shower Rail, 300mm Rose, Single Function Hand Shower'),
  ('MZ0706-R-PVDGM', 'Round Combination Shower Rail, 300mm Rose, Single Function Hand Shower'),
  ('MZ07B', 'MZ0704/MZ0704-R/MZ0706/MZ0706-R complete shower rail including shower hose only excluding shower rose and hand shower'),
  ('MZ07B-C', 'MZ0704/MZ0704-R/MZ0706/MZ0706-R complete shower rail including shower hose only excluding shower rose and hand shower'),
  ('MZ07B-CH', 'MZ0704/MZ0704-R/MZ0706/MZ0706-R complete shower rail including shower hose only excluding shower rose and hand shower'),
  ('MZ07B-PVDBB', 'MZ0704/MZ0704-R/MZ0706/MZ0706-R complete shower rail including shower hose only excluding shower rose and hand shower'),
  ('MZ07B-PVDBN', 'MZ0704/MZ0704-R/MZ0706/MZ0706-R complete shower rail including shower hose only excluding shower rose and hand shower'),
  ('MZ07B-PVDBZ', 'MZ0704/MZ0704-R/MZ0706/MZ0706-R complete shower rail including shower hose only excluding shower rose and hand shower'),
  ('MZ07B-PVDGM', 'MZ0704/MZ0704-R/MZ0706/MZ0706-R complete shower rail including shower hose only excluding shower rose and hand shower'),
  ('MZ08', 'Round Three Function Hand Shower on Fixed Bracket'),
  ('MZ08-C', 'Round Three Function Hand Shower on Fixed Bracket'),
  ('MZ08-CH', 'Round Three Function Hand Shower on Fixed Bracket'),
  ('MZ08-PVDBB', 'Round Three Function Hand Shower on Fixed Bracket'),
  ('MZ08-PVDBN', 'Round Three Function Hand Shower on Fixed Bracket'),
  ('MZ08-PVDBZ', 'Round Three Function Hand Shower on Fixed Bracket'),
  ('MZ08-PVDGM', 'Round Three Function Hand Shower on Fixed Bracket'),
  ('MZ08-R', 'Round Hand Shower on Fixed Bracket'),
  ('MZ08-R-C', 'Round Hand Shower on Fixed Bracket'),
  ('MZ08-R-CH', 'Round Hand Shower on Fixed Bracket'),
  ('MZ08-R-PVDBB', 'Round Hand Shower on Fixed Bracket'),
  ('MZ08-R-PVDBN', 'Round Hand Shower on Fixed Bracket'),
  ('MZ08-R-PVDBZ', 'Round Hand Shower on Fixed Bracket'),
  ('MZ08-R-PVDGM', 'Round Hand Shower on Fixed Bracket'),
  ('MZ08B', 'MZ08/MZ08-R complete bracket and hose only excluding the hand shower'),
  ('MZ08B-C', 'MZ08/MZ08-R complete bracket and hose only excluding the hand shower'),
  ('MZ08B-CH', 'MZ08/MZ08-R complete bracket and hose only excluding the hand shower'),
  ('MZ08B-PVDBB', 'MZ08/MZ08-R complete bracket and hose only excluding the hand shower'),
  ('MZ08B-PVDBN', 'MZ08/MZ08-R complete bracket and hose only excluding the hand shower'),
  ('MZ08B-PVDBZ', 'MZ08/MZ08-R complete bracket and hose only excluding the hand shower'),
  ('MZ08B-PVDGM', 'MZ08/MZ08-R complete bracket and hose only excluding the hand shower'),
  ('MZ0904', '200mm Round Overhead Shower Rail, Three Function Hand Shower'),
  ('MZ0904-C', '200mm Round Overhead Shower Rail, Three Function Hand Shower'),
  ('MZ0904-CH', '200mm Round Overhead Shower Rail, Three Function Hand Shower'),
  ('MZ0904-PVDBB', '200mm Round Overhead Shower Rail, Three Function Hand Shower'),
  ('MZ0904-PVDBN', '200mm Round Overhead Shower Rail, Three Function Hand Shower'),
  ('MZ0904-PVDBZ', '200mm Round Overhead Shower Rail, Three Function Hand Shower'),
  ('MZ0904-PVDGM', '200mm Round Overhead Shower Rail, Three Function Hand Shower'),
  ('MZ0904-R', '200mm Round Overhead Shower Set, Single Function Hand Shower'),
  ('MZ0904-R-C', '200mm Round Overhead Shower Set, Single Function Hand Shower'),
  ('MZ0904-R-CH', '200mm Round Overhead Shower Set, Single Function Hand Shower'),
  ('MZ0904-R-PVDBB', '200mm Round Overhead Shower Set, Single Function Hand Shower')
ON CONFLICT (sku_code) DO UPDATE SET sku_name = EXCLUDED.sku_name;

INSERT INTO products (sku_code, sku_name) VALUES
  ('MZ0904-R-PVDBN', '200mm Round Overhead Shower Set, Single Function Hand Shower'),
  ('MZ0904-R-PVDBZ', '200mm Round Overhead Shower Set, Single Function Hand Shower'),
  ('MZ0904-R-PVDGM', '200mm Round Overhead Shower Set, Single Function Hand Shower'),
  ('MZ0906', '300mm Round Overhead Shower Rail, Three Function Hand Shower'),
  ('MZ0906-C', '300mm Round Overhead Shower Rail, Three Function Hand Shower'),
  ('MZ0906-CH', '300mm Round Overhead Shower Rail, Three Function Hand Shower'),
  ('MZ0906-PVDBB', '300mm Round Overhead Shower Rail, Three Function Hand Shower'),
  ('MZ0906-PVDBN', '300mm Round Overhead Shower Rail, Three Function Hand Shower'),
  ('MZ0906-PVDBZ', '300mm Round Overhead Shower Rail, Three Function Hand Shower'),
  ('MZ0906-PVDGM', '300mm Round Overhead Shower Rail, Three Function Hand Shower'),
  ('MZ0906-R', '300mm Round Overhead Shower Set, Single Function Hand Shower'),
  ('MZ0906-R-C', '300mm Round Overhead Shower Set, Single Function Hand Shower'),
  ('MZ0906-R-CH', '300mm Round Overhead Shower Set, Single Function Hand Shower'),
  ('MZ0906-R-PVDBB', '300mm Round Overhead Shower Set, Single Function Hand Shower'),
  ('MZ0906-R-PVDBN', '300mm Round Overhead Shower Set, Single Function Hand Shower'),
  ('MZ0906-R-PVDBZ', '300mm Round Overhead Shower Set, Single Function Hand Shower'),
  ('MZ0906-R-PVDGM', '300mm Round Overhead Shower Set, Single Function Hand Shower'),
  ('MZ09B', 'Twin shower rail set. Curved overhead shower arm, including the hose, but excluding the shower head and hand shower'),
  ('MZ09B-C', 'Twin shower rail set. Curved overhead shower arm, including the hose, but excluding the shower head and hand shower'),
  ('MZ09B-CH', 'Twin shower rail set. Curved overhead shower arm, including the hose, but excluding the shower head and hand shower'),
  ('MZ09B-PVDBB', 'Twin shower rail set. Curved overhead shower arm, including the hose, but excluding the shower head and hand shower'),
  ('MZ09B-PVDBN', 'Twin shower rail set. Curved overhead shower arm, including the hose, but excluding the shower head and hand shower'),
  ('MZ09B-PVDBZ', 'Twin shower rail set. Curved overhead shower arm, including the hose, but excluding the shower head and hand shower'),
  ('MZ09B-PVDGM', 'Twin shower rail set. Curved overhead shower arm, including the hose, but excluding the shower head and hand shower'),
  ('MZ09B-SPOUT-CH', 'MZ09B-CH Curved overhead shower arm/spout only'),
  ('MZ1004N-R-SS316', 'Outdoor Combination Shower Rail SS316'),
  ('MZ10N-DBP-SS316', 'Diverter Back Plate, Parts 14,15,31 for Meir Outdoor Twin Combination Shower Stainless Steel'),
  ('NB-MD01', 'Round Colour Sample Disc no box'),
  ('NB-MD01-C', 'Round Colour Sample Disc no box XXX'),
  ('NB-MD01-CH', 'Round Colour Sample Disc no box'),
  ('NB-MD01-PVDBB', 'Round Colour Sample Disc no box'),
  ('NB-MD01-PVDBN', 'Round Colour Sample Disc no box'),
  ('NB-MD01-PVDBZ', 'Round Colour Sample Disc'),
  ('NB-MD01-PVDGM', 'Round Colour Sample Disc no box XXX'),
  ('NB-MD01-PVDGMS', 'Round Colour Sample Disc no box XXX'),
  ('NB-MD01-SS316', 'Round Colour Sample Disc no box'),
  ('NB-MD01.01-PVDBZ', 'Round Colour Sample Disc'),
  ('NB-MD01.02', 'Round Colour Sample Disc no box'),
  ('NB-MD01.02-C', 'Round Colour Sample Disc no box'),
  ('NB-MD01.02-CH', 'Round Colour Sample Disc no box'),
  ('NB-MD01.02-PVDBB', 'Round Colour Sample Disc no box'),
  ('NB-MD01.02-PVDBN', 'Round Colour Sample Disc no box'),
  ('NB-MD01.02-PVDBZ', 'Round Colour Sample Disc no box'),
  ('NB-MD01.02-PVDGM', 'Round Colour Sample Disc no box GUN METAL'),
  ('NB-MD02-PVDBB', 'Sample Disc for Sinks no box'),
  ('NB-MD02-PVDBN', 'Sample Disc for Sinks no box'),
  ('NB-MD02-PVDGM', 'Sample Disc for Sinks no box'),
  ('NB-MD02-SS304', 'Sample Disc for Sinks no box'),
  ('NB-MD03-PVDBB', 'Sample Disc for Basins no box'),
  ('NB-MD03-PVDBN', 'Sample Disc for Basins no box')
ON CONFLICT (sku_code) DO UPDATE SET sku_name = EXCLUDED.sku_name;

INSERT INTO products (sku_code, sku_name) VALUES
  ('NB-MD03-PVDCH', 'Sample Disc for Basins no box'),
  ('NB-MD03-PVDGM', 'No Box Basin Sample Disc SA/NL Only'),
  ('NB-MD03-PVDGMS', 'Sample Disc for Basins no box'),
  ('P027006-01-20', '20mm Fitting for wall taps MW11 no screws (singles)'),
  ('P027006-01-25', '25mm Fitting for wall taps MW04, MW05, MW06, MW08JL (need to use 2 per set of taps) no screws'),
  ('RM-01', 'Lavello Stainless Steel rolling mat protector'),
  ('RM-01-GM', 'Lavello Stainless Steel rolling mat protector'),
  ('RM-01-PVDBB', 'Lavello Stainless Steel rolling mat protector'),
  ('RM-01-PVDGM', 'Lavello Stainless Steel rolling mat protector'),
  ('SAMPLE-DH', 'Matte Diverter Handle Sample'),
  ('SAMPLE-DH-C', 'Chrome Diverter Handle Sample'),
  ('SAMPLE-DH-CH', 'Champagne Diverter Handle Sample'),
  ('SAMPLE-DH-PVDBB', 'PVD Diverter Handle Sample'),
  ('SAMPLE-DH-PVDBN', 'Diverter Handle Sample'),
  ('SAMPLE-DH-PVDBZ', 'SAMPLE-DH-PVDBZ - Diverter handle'),
  ('SAMPLE-DH-PVDGM', 'Shadow Diverter Handle Sample'),
  ('SAMPLE-H', 'Matte Cross Handle Sample'),
  ('SAMPLE-H-C', 'Chrome Cross Handle Sample'),
  ('SAMPLE-H-CH', 'Champagne Cross Handle Sample'),
  ('SAMPLE-H-PVDBB', 'Cross Handle Sample'),
  ('SAMPLE-H-PVDBN', 'Cross Handle Sample'),
  ('SAMPLE-H-PVDGM', 'Cross Handle Sample'),
  ('MST01-DMB02', 'Clear Display Stand with Fitting for Dummy Display DMB02'),
  ('MST01-DMB02-CH', 'Clear Display Stand with Fitting for Dummy Display DMB02-CH'),
  ('MST01-DMB02-PVDBB', 'Clear Display Stand with Fitting for Dummy Display DMB02-PVDBB'),
  ('MST01-DMB02-PVDBN', 'Clear Display Stand with Fitting for Dummy Display DMB02-PVDBN'),
  ('MST01-MB02', 'Clear Display Stand with Fitting for MB02'),
  ('MST01-MB02-C', 'Clear Display Stand with Fitting for MB02-C'),
  ('MST01-MB02-CH', 'Clear Display Stand with Fitting for MB02-CH'),
  ('MST01-MB02-PVDBB', 'Clear Display Stand with Fitting for MB02-PVDBB'),
  ('MST01-MB02-PVDBN', 'Clear Display Stand with Fitting for MB02-PVDBN'),
  ('MST01-MB02-PVDGM', 'Clear Display Stand with Fitting for MB02-PVDGM'),
  ('MST01-MB03', 'Clear Display Stand with Fitting for MB03'),
  ('MST01-MB03-PVDBN', 'Clear Display Stand with Fitting for MB03-PVDBN'),
  ('MST01-MB03-PVDBZ', 'Clear Display Stand with Fitting for MB03-PVDBZ'),
  ('MST01-MB03XL.01', 'Clear Display Stand with Fitting for MB03XL.01'),
  ('MST01-MB03XL.01-C', 'Clear Display Stand with Fitting for MB03XL.01-C'),
  ('MST01-MB03XL.01-CH', 'Clear Display Stand with Fitting for MB03XL.01-CH'),
  ('MST01-MB03XL.01-PVDBB', 'Clear Display Stand with Fitting for MB03XL.01-PVDBB'),
  ('MST01-MB03XL.01-PVDBN', 'Clear Display Stand with Fitting for MB03XL.01-PVDBN'),
  ('MST01-MB03XL.01-PVDBZ', 'Clear Display Stand with Fitting for MB03XL.01-PVDBZ'),
  ('MST01-MB03XL.01-PVDGM', 'Clear Display Stand with Fitting for MB03XL.01-PVDGM'),
  ('MST01-MB03XS', 'Clear Display Stand with Fitting for MB03XS'),
  ('MST01-MB03XS-C', 'Clear Display Stand with Fitting for MB03XS-C'),
  ('MST01-MB03XS-CH', 'Clear Display Stand with Fitting for MB03XS-CH'),
  ('MST01-MB03XS-PVDBB', 'Clear Display Stand with Fitting for MB03XS-PVDBB'),
  ('MST01-MB03XS-PVDBN', 'Clear Display Stand with Fitting for MB03XS-PVDBN'),
  ('MST01-MB03XS-PVDGM', 'Clear Display Stand with Fitting for MB03XS-PVDGM'),
  ('MST01-MB17', 'Clear Display Stand with Fitting for MB17'),
  ('MST01-MB17-C', 'Clear Display Stand with Fitting for MB17-C')
ON CONFLICT (sku_code) DO UPDATE SET sku_name = EXCLUDED.sku_name;

INSERT INTO products (sku_code, sku_name) VALUES
  ('MST01-MB17-CH', 'Clear Display Stand with Fitting for MB17-CH'),
  ('MST01-MB17-PVDBB', 'Clear Display Stand with Fitting for MB17-PVDBB'),
  ('MST01-MB17-PVDBN', 'Clear Display Stand with Fitting for MB17-PVDBN'),
  ('MST01-MB17-PVDBZ', 'Clear Display Stand with Fitting for MB17-PVDBZ'),
  ('MST01-MB17-PVDGM', 'Clear Display Stand with Fitting for MB17-PVDGM'),
  ('Oppen-Display-Board-CH', 'Oppen-Display-Board-CH'),
  ('Oppen-Display-Board-PVDBB', 'Oppen-Display-Board-PVDBB'),
  ('Oppen-Display-Board-PVDBN', 'Oppen-Display-Board-PVDBN'),
  ('Oppen-Display-Board-PVDBZ', 'Oppen-Display-Board-PVDBZ'),
  ('Oppen-Display-Board-PVDGM', 'Oppen-Display-Board-PVDGM'),
  ('DMW-Part1', 'Mounting Display Fittings and Screw for wall mixers such as MW01, MW02, MW03, MW07 and MW07TS (use x1 per Mixer)'),
  ('MW03-FIN Display Fitting', 'MW03-FIN display fittings'),
  ('838076', 'Plastic connectors for the display boards'),
  ('MDB01.01', 'Sample Box Diverter Handles set of 7'),
  ('DMW18-PVDBZ', 'Dummy Progressive Mixer with collar'),
  ('DMW18', 'Dummy Progressive Mixer with collar'),
  ('DMW18-PVDBB', 'Dummy Progressive Mixer with collar'),
  ('DMW18PVDBN', ''),
  ('DMW18-PVDGM', 'Dummy Progressive Mixer with collar'),
  ('DMW18-C', 'Dummy Progressive Mixer with collar'),
  ('DMW18-CH', 'Dummy Progressive Mixer with collar'),
  ('MST01-MB03-PVDBB', 'Clear Display Stand with Fitting for MB03-PVDBB'),
  ('MBPN-H-PVDGM', 'Pinless handle 45mm for MB02, MB04-R2'),
  ('M44*1.5', 'Basin mixer stand installation fitting & for MST01'),
  ('MST01-MB02-PVDBZ', 'Clear Display Stand with Fitting for MB02-PVDBZ'),
  ('MST01-MB03-PVDGM', 'Clear Display Stand with Fitting for MB03-PVDGM'),
  ('MST01-MB03-CH', 'Clear Display Stand with Fitting for MB03-CH'),
  ('MST01-MB03-C', 'Clear Display Stand with Fitting for MB03-C'),
  ('MWPD-H', 'Paddle handle 42mm for MW03, MW07TS'),
  ('MWPN-H', 'Pinless handle 42mm for MW03, MW07TS'),
  ('MKPD-H', 'Paddle handle 40mm for MK03, MK17'),
  ('MKPN-H', 'Pinless handle 40mm for MK03, MK17'),
  ('MBPD-H', 'Paddle handle 45mm for MB02, MB04-R2'),
  ('MBPN-H', 'Pinless handle 45mm for MB02, MB04-R2'),
  ('MBPD-H-MB09', 'Paddle handle 45mm for MB09'),
  ('MBPN-H-MB09', 'Pinless handle 45mm for MB09'),
  ('MWPD-H-C', 'Paddle handle 42mm for MW03, MW07TS'),
  ('MWPN-H-C', 'Pinless handle 42mm for MW03, MW07TS'),
  ('MKPD-H-C', 'Paddle handle 40mm for MK03, MK17'),
  ('MKPN-H-C', 'Pinless handle 40mm for MK03, MK17'),
  ('MBPD-H-C', 'Paddle handle 45mm for MB02, MB04-R2'),
  ('MBPN-H-C', 'Pinless handle 45mm for MB02, MB04-R2'),
  ('MBPD-H-MB09-C', 'Paddle handle 45mm for MB09'),
  ('MBPN-H-MB09-C', 'Pinless handle 45mm for MB09'),
  ('MWPD-H-CH', 'Paddle handle 42mm for MW03, MW07TS'),
  ('MWPN-H-CH', 'Pinless handle 42mm for MW03, MW07TS'),
  ('MKPD-H-CH', 'Paddle handle 40mm for MK03, MK17'),
  ('MKPN-H-CH', 'Pinless handle 40mm for MK03, MK17'),
  ('MBPD-H-CH', 'Paddle handle 45mm for MB02, MB04-R2'),
  ('MBPN-H-CH', 'Pinless handle 45mm for MB02, MB04-R2')
ON CONFLICT (sku_code) DO UPDATE SET sku_name = EXCLUDED.sku_name;

INSERT INTO products (sku_code, sku_name) VALUES
  ('MBPD-H-MB09-CH', 'Paddle handle 45mm for MB09'),
  ('MBPN-H-MB09-CH', 'Pinless handle 45mm for MB09'),
  ('MWPD-H-PVDBN', 'Paddle handle 42mm for MW03, MW07TS'),
  ('MWPN-H-PVDBN', 'Pinless handle 42mm for MW03, MW07TS'),
  ('MKPD-H-PVDBN', 'Paddle handle 40mm for MK03, MK17'),
  ('MKPN-H-PVDBN', 'Pinless handle 40mm for MK03, MK17'),
  ('MBPD-H-PVDBN', 'Paddle handle 45mm for MB02, MB04-R2'),
  ('MBPN-H-PVDBN', 'Pinless handle 45mm for MB02, MB04-R2'),
  ('MBPD-H-MB09-PVDBN', 'Paddle handle 45mm for MB09'),
  ('MBPN-H-MB09-PVDBN', 'Pinless handle 45mm for MB09'),
  ('MWPD-H-PVDBB', 'Paddle handle 42mm for MW03, MW07TS'),
  ('MWPN-H-PVDBB', 'Pinless handle 42mm for MW03, MW07TS'),
  ('MKPD-H-PVDBB', 'Paddle handle 40mm for MK03, MK17'),
  ('MKPN-H-PVDBB', 'Pinless handle 40mm for MK03, MK17'),
  ('MBPD-H-PVDBB', 'Paddle handle 45mm for MB02, MB04-R2'),
  ('MBPN-H-PVDBB', 'Pinless handle 45mm for MB02, MB04-R2'),
  ('MBPD-H-MB09-PVDBB', 'Paddle handle 45mm for MB09'),
  ('MBPN-H-MB09-PVDBB', 'Pinless handle 45mm for MB09'),
  ('MWPD-H-PVDGM', 'Paddle handle 42mm for MW03, MW07TS'),
  ('MWPN-H-PVDGM', 'Pinless handle 42mm for MW03, MW07TS'),
  ('MKPD-H-PVDGM', 'Paddle handle 40mm for MK03, MK17'),
  ('MKPN-H-PVDGM', 'Pinless handle 40mm for MK03, MK17'),
  ('MBPD-H-PVDGM', 'Paddle handle 45mm for MB02, MB04-R2'),
  ('MBPD-H-MB09-PVDGM', 'Paddle handle 45mm for MB09'),
  ('MBPN-H-MB09-PVDGM', 'Pinless handle 45mm for MB09'),
  ('MWPD-H-PVDBZ', 'Paddle handle 42mm for MW03, MW07TS'),
  ('MWPN-H-PVDBZ', 'Pinless handle 42mm for MW03, MW07TS'),
  ('MKPD-H-PVDBZ', 'Paddle handle 40mm for MK03, MK17'),
  ('MKPN-H-PVDBZ', 'Pinless handle 40mm for MK03, MK17'),
  ('MBPD-H-PVDBZ', 'Paddle handle 45mm for MB02, MB04-R2'),
  ('MBPN-H-PVDBZ', 'Pinless handle 45mm for MB02, MB04-R2'),
  ('MBPD-H-MB09-PVDBZ', 'Paddle handle 45mm for MB09'),
  ('MBPN-H-MB09-PVDBZ', 'Pinless handle 45mm for MB09'),
  ('M32*1.5', 'KP01.010 Stand installation fitting for MST01'),
  ('M38*1.5', 'P6814 XXX MB03XS Stand installation fitting for MST01'),
  ('M40*1.5', 'Display Mounting Parts for the MB17 XXX P6815'),
  ('830003', '830003 - bolt (B99) used for MB03XS Stand installation on MST01'),
  ('DHB03-PVDBN', 'DUMMY Harrington Short Basin Mixer - PVD Brushed Nickel'),
  ('MST01-DHB03-PVDBN', 'Clear Display Stand with Fitting for DHB03-PVDBN'),
  ('MA02-400-P-C', 'Shower Arm Back Plate'),
  ('MA02-400-P-PVDBZ', 'MA02-400 back plate'),
  ('MA02-400-P-PVDGM', 'MA02-400 back plate'),
  ('MA07-150-P', 'MA07-150 Back Plate'),
  ('MA07-150-P-C', 'MA07-150 Back Plate'),
  ('MA07-150-P-CH', 'MA07-150 Back Plate'),
  ('MA07-150-P-PVDBB', 'MA07-150 Back Plate'),
  ('MA07-150-P-PVDBZ', 'MA07-150 Back Plate'),
  ('MA07-150-P-PVDGM', 'MA07-150 Back Plate'),
  ('MA07-P-CH', 'Shower Arm Back plate for MA07-300-CH'),
  ('MA07-P-PVDBB', 'Shower Arm Back plate')
ON CONFLICT (sku_code) DO UPDATE SET sku_name = EXCLUDED.sku_name;

INSERT INTO products (sku_code, sku_name) VALUES
  ('MA07-P-PVDBN', 'Shower Arm Back plate'),
  ('MA07-P-PVDGM', 'Shower Arm Back plate'),
  ('MA09-P70-PVDBZ', 'Shower Arm Back Plate 70mm'),
  ('MA09-P70-PVDGM', 'Shower Arm Back Plate 70mm'),
  ('MB09-P', 'MB09 Back Plate Matte'),
  ('MB09-P-C', 'MB09 Back Plate'),
  ('MB09-P-CH', 'MB09 Back Plate'),
  ('MB10-HBP', 'MB10- Handle Backplate'),
  ('MB17-P', 'MB17/MK17 Back Plate / Dressing Ring'),
  ('MB17-P-C', 'MB17/MK17 Back Plate / Dressing Ring'),
  ('MB17-P-CH', 'MB17/MK17 Back Plate / Dressing Ring'),
  ('MB17-P-PVDBB', 'MB17/MK17 Back Plate / Dressing Ring PVDBB'),
  ('MB17-P-PVDBN', 'MB17/MK17 Back Plate / Dressing Ring PVDBN'),
  ('MB17-P-PVDGM', 'MB17/MK17 Back Plate / Dressing Ring PVDGM'),
  ('MS05-P70', '70mm Back Plate for MS05/MS07/MS16/MA09/KP14.020 P043410BK'),
  ('MS05-P70-C', '70mm Back Plate for MS05/MS07/MS16/MA09/KP14.020 P043410'),
  ('MS05-P70-CH', '70mm Back Plate for MS05/MS07/MS16/MA09/KP14.020 P043410CH'),
  ('MS05-P70-PVDBB', '70mm Back Plate for MS05/MS07/MS16/MA09/KP14.020 P043410PVDBB'),
  ('MS05-P70-PVDBN', '70mm Back Plate for MS05/MS07/MS16/MA09/KP14.020 P043410BN'),
  ('MS05-P70-PVDBZ', '70mm Back Plate for MS05/MS07/MS16/MA09/KP14.020 P043410BZ'),
  ('MS05-P70-PVDGM', '70mm Back Plate for MS05/MS07/MS16/MA09/KP14.020 P043410PVDGM'),
  ('MW08JL-P70', 'MW08JL/MW06 70mm backplate ONLY (P028001BK)'),
  ('MW08JL-P70-C', 'MW08JL-C / MW06-C 70mm Back plate'),
  ('MW08JL-P70-CH', 'MW08JL-CH/MW06-CH 70mm Back plate'),
  ('MW08JL-P70-PVDBB', 'MW08JL-PVDBB/MW06-PVDBB 70mm Back plate'),
  ('MW08JL-P70-PVDBN', 'MW08JL-PVDBN/MW06-PVDBN 70mm Back plate'),
  ('MW08JL-P70-PVDBZ', 'MW08JL-PVDBN/MW06-PVDBN 70mm Back plate'),
  ('MW08JL-P70-PVDGM', 'MW08JL-PVDGM/MW06-PVDGM 70mm Back plate'),
  ('MW11-P-PVDBB', 'MW11 Back Plate (1 PCS) Parts 4 & 5'),
  ('MB03XL.01-PVDBB', ''),
  ('MB03XL.01-PVDBN', ''),
  ('MCR-40LH70-CH', ''),
  ('MCR-40LH70-PVDBB', ''),
  ('MCR-40LH70-PVDBN', ''),
  ('MCR-40LH70-PVDBZ', ''),
  ('MCR-40RH70-CH', ''),
  ('MCR-40RH70-PVDBB', ''),
  ('MCR-40RH70-PVDBN', ''),
  ('MCR-40RH70-PVDBZ', ''),
  ('MCR-90LH60-CH', ''),
  ('MCR-90LH60-PVDBB', ''),
  ('MCR-90LH60-PVDBN', ''),
  ('MCR-90LH60-PVDBZ', ''),
  ('MCR-90R45-CH', ''),
  ('MCR-90R45-PVDBB', ''),
  ('MCR-90R45-PVDBN', ''),
  ('MCR-90R45-PVDBZ', ''),
  ('MCR-90RH60-CH', ''),
  ('MCR-90RH60-PVDBB', ''),
  ('MCR-90RH60-PVDBN', '')
ON CONFLICT (sku_code) DO UPDATE SET sku_name = EXCLUDED.sku_name;

INSERT INTO products (sku_code, sku_name) VALUES
  ('MCR-90RH60-PVDBZ', ''),
  ('MCR-H42-CH', ''),
  ('MCR-H42-PVDBB', ''),
  ('MCR-H42-PVDBN', ''),
  ('MCR-H42-PVDBZ', ''),
  ('MCR-REST-CH', ''),
  ('MCR-REST-PVDBB', ''),
  ('MCR-REST-PVDBN', ''),
  ('MCR-REST-PVDBZ', ''),
  ('MCR-SEAT-CH', ''),
  ('MCR-SEAT-PVDBB', ''),
  ('MCR-SEAT-PVDBN', ''),
  ('MCR-SEAT-PVDBZ', ''),
  ('MCR-SHOWER-CH', ''),
  ('MCR-SHOWER-PVDBB', ''),
  ('MCR-SHOWER-PVDBN', ''),
  ('MCR-SHOWER-PVDBZ', ''),
  ('MCR-SR30-CH', ''),
  ('MCR-SR30-PVDBB', ''),
  ('MCR-SR30-PVDBN', ''),
  ('MCR-SR30-PVDBZ', ''),
  ('MCR-SR60-CH', ''),
  ('MCR-SR60-PVDBB', ''),
  ('MCR-SR60-PVDBN', ''),
  ('MCR-SR60-PVDBZ', ''),
  ('MCR-SR90-CH', ''),
  ('MCR-SR90-PVDBB', ''),
  ('MCR-SR90-PVDBN', ''),
  ('MCR-SR90-PVDBZ', ''),
  ('MCR-TPH-CH', ''),
  ('MCR-TPH-PVDBB', ''),
  ('MCR-TPH-PVDBN', ''),
  ('MCR-TPH-PVDBZ', ''),
  ('MCR-TR28-CH', ''),
  ('MCR-TR28-PVDBB', ''),
  ('MCR-TR28-PVDBN', ''),
  ('MCR-TR28-PVDBZ', ''),
  ('MCR-TR75-CH', ''),
  ('MCR-TR75-PVDBB', ''),
  ('MCR-TR75-PVDBN', ''),
  ('MCR-TR75-PVDBZ', ''),
  ('MD01.02-SETSA', ''),
  ('MDS02-CH', 'Round Door Stop'),
  ('MDS02-PVDBB', 'Round Door Stop'),
  ('MDS02-PVDBN', 'Round Door Stop'),
  ('MDS02-PVDBZ', 'Round Door Stop'),
  ('MDS02-PVDGM', 'Round Door Stop'),
  ('MDS03-PVDBB', ''),
  ('MHB03N', ''),
  ('MHB03N-C', '')
ON CONFLICT (sku_code) DO UPDATE SET sku_name = EXCLUDED.sku_name;

INSERT INTO products (sku_code, sku_name) VALUES
  ('MHB03N-CH', ''),
  ('MHB03N-PVDBB', ''),
  ('MHB03N-PVDBN', ''),
  ('MHB03N-PVDBZ', ''),
  ('MHB03N-PVDGM', ''),
  ('MHT02B', ''),
  ('MK02', ''),
  ('MK02-C', ''),
  ('MK19', ''),
  ('MK19-C', ''),
  ('MK19-CH', ''),
  ('MK19-PVDBB', ''),
  ('MK19-PVDBN', ''),
  ('MK19-PVDBZ', ''),
  ('MK19-PVDGM', ''),
  ('MK21', ''),
  ('MK21-C', ''),
  ('MK21-CH', ''),
  ('MK21-PVDBB', ''),
  ('MK21-PVDBN', ''),
  ('MK21-PVDBZ', ''),
  ('MK21-PVDGM', ''),
  ('MKSP-S840440D-PVDBN', ''),
  ('MKSP-S840440D-PVDGM', ''),
  ('MP06F-T900-CH', ''),
  ('MP06F-T900-PVDBB', ''),
  ('MP06F-T900-PVDBN', ''),
  ('MP06F-T900-PVDBZ', ''),
  ('MP06F-T900-PVDGM', ''),
  ('MP09', ''),
  ('MP09-PVDBB', ''),
  ('MP09-PVDBZ', ''),
  ('MP10N-CH', ''),
  ('MP10N-PVDBB', ''),
  ('MP10N-PVDBN', ''),
  ('MP10N-PVDBZ', ''),
  ('MP10N-PVDGM', ''),
  ('MP11PN', ''),
  ('MP11PN-C', ''),
  ('MP11PN-CH', ''),
  ('MP11PN-PVDBB', ''),
  ('MP11PN-PVDBN', ''),
  ('MP11PN-PVDBZ', ''),
  ('MP11PN-PVDGM', ''),
  ('MP18', ''),
  ('MR08', ''),
  ('MRTR-3S80N', ''),
  ('MRTR-3S80N-C', ''),
  ('MRTR-3S80N-CH', ''),
  ('MRTR-3S80N-PVDBB', '')
ON CONFLICT (sku_code) DO UPDATE SET sku_name = EXCLUDED.sku_name;

INSERT INTO products (sku_code, sku_name) VALUES
  ('MRTR-3S80N-PVDBN', ''),
  ('MRTR-3S80N-PVDBZ', ''),
  ('MRTR-3S80N-PVDGM', ''),
  ('MS05-170', ''),
  ('MS05-170-C', ''),
  ('MS05-170-CH', ''),
  ('MS05-170-PVDBB', ''),
  ('MS05-170-PVDBN', ''),
  ('MS05-170-PVDBZ', ''),
  ('MS05-170-PVDGM', ''),
  ('MS18', ''),
  ('MS18-C', ''),
  ('MS18-CH', ''),
  ('MS18-PVDBB', ''),
  ('MS18-PVDBN', ''),
  ('MS18-PVDBZ', ''),
  ('MS18-PVDGM', ''),
  ('MW07TSPD-FIN', ''),
  ('MW07TSPD-FIN-C', ''),
  ('MW07TSPD-FIN-CH', ''),
  ('MW07TSPD-FIN-PVDBB', ''),
  ('MW07TSPD-FIN-PVDBN', ''),
  ('MW07TSPD-FIN-PVDBZ', ''),
  ('MW07TSPD-FIN-PVDGM', ''),
  ('MW07TSPN-FIN', ''),
  ('MW07TSPN-FIN-C', ''),
  ('MW07TSPN-FIN-CH', ''),
  ('MW07TSPN-FIN-PVDBB', ''),
  ('MW07TSPN-FIN-PVDBN', ''),
  ('MW07TSPN-FIN-PVDBZ', ''),
  ('MW07TSPN-FIN-PVDGM', ''),
  ('MW13BDY', ''),
  ('MW13BDY-EXT', ''),
  ('DMW18-PVDBN', ''),
  ('MW27BDY', ''),
  ('MW27BDY-EXT', ''),
  ('MZ06N-R-SS316', ''),
  ('NB-MD01.02-PVDGMS', ''),
  ('NB-MD01.02-SS316', ''),
  ('P-SUB-003', ''),
  ('AB03-BB.BL', ''),
  ('AB03-BB.MG', ''),
  ('AB03-BB.ND', ''),
  ('AB03-BN.ND', ''),
  ('AB03-BN.OL', ''),
  ('AB03-BN.SL', ''),
  ('AB03-BZ.CL', ''),
  ('AB03-BZ.OL', ''),
  ('AB03-BZ.ST', ''),
  ('AB03-CH.LP', '')
ON CONFLICT (sku_code) DO UPDATE SET sku_name = EXCLUDED.sku_name;

INSERT INTO products (sku_code, sku_name) VALUES
  ('AB03-CH.MS', ''),
  ('AB03-CH.MU', ''),
  ('ACB03-BB.BL', ''),
  ('ACB03-BB.MG', ''),
  ('ACB03-BB.ND', ''),
  ('ACB03-BN.ND', ''),
  ('ACB03-BN.OL', ''),
  ('ACB03-BN.SL', ''),
  ('ACB03-BZ.CL', ''),
  ('ACB03-BZ.OL', ''),
  ('ACB03-BZ.ST', ''),
  ('ACB03-CH.LP', ''),
  ('ACB03-CH.MS', ''),
  ('ACB03-CH.MU', ''),
  ('AW18-BB.BL', ''),
  ('AW18-BB.MG', ''),
  ('AW18-BB.ND', ''),
  ('AW18-BN.ND', ''),
  ('AW18-BN.OL', ''),
  ('AW18-BN.SL', ''),
  ('AW18-BZ.CL', ''),
  ('AW18-BZ.OL', ''),
  ('AW18-BZ.ST', ''),
  ('AW18-CH.LP', ''),
  ('AW18-CH.MS', ''),
  ('AW18-CH.MU', ''),
  ('BA02-BK', ''),
  ('BA02-BN', ''),
  ('BA02-CR', ''),
  ('BA07-BK', ''),
  ('BA07-BN', ''),
  ('BA07-CR', ''),
  ('BB02-BK', ''),
  ('BB02-BN', ''),
  ('BB02-CR', ''),
  ('BCB03-FIN-BK', ''),
  ('BCB03-FIN-BN', ''),
  ('BCB03-FIN-CR', ''),
  ('BH04-BK', ''),
  ('BH04-BN', ''),
  ('BH04-CR', ''),
  ('BK17-BK', ''),
  ('BK17-BN', ''),
  ('BK17-CR', ''),
  ('BRRH-S-BK', ''),
  ('BRRH-S-BN', ''),
  ('BRRH-S-CR', ''),
  ('BRTP-S-BK', ''),
  ('BRTP-S-BN', ''),
  ('BRTP-S-CR', '')
ON CONFLICT (sku_code) DO UPDATE SET sku_name = EXCLUDED.sku_name;

INSERT INTO products (sku_code, sku_name) VALUES
  ('BRTR-S60-BK', ''),
  ('BRTR-S60-BN', ''),
  ('BRTR-S60-CR', ''),
  ('BW03-FIN-BK', ''),
  ('BW03-FIN-BN', ''),
  ('BW03-FIN-CR', ''),
  ('BW07-FIN-BK', ''),
  ('BW07-FIN-BN', ''),
  ('BW07-FIN-CR', ''),
  ('BW13BDY', ''),
  ('BW15BDY', ''),
  ('BW27BDY', ''),
  ('BZ04-BK', ''),
  ('BZ04-BN', ''),
  ('BZ04-CR', ''),
  ('BZ07-BK', ''),
  ('BZ07-BN', ''),
  ('BZ07-CR', '')
ON CONFLICT (sku_code) DO UPDATE SET sku_name = EXCLUDED.sku_name;


-- ============================================================
-- DISPLAY FITTINGS TABLE (parts auto-added to orders by prefix)
-- ============================================================

CREATE TABLE IF NOT EXISTS display_fittings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  fitting_sku TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  qty_per_sku INTEGER NOT NULL DEFAULT 1,
  trigger_prefixes TEXT[] NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE display_fittings ENABLE ROW LEVEL SECURITY;
CREATE POLICY fittings_select ON display_fittings FOR SELECT USING (true);

INSERT INTO display_fittings (fitting_sku, description, qty_per_sku, trigger_prefixes) VALUES
  ('P027006-01-25', '25mm Fitting for wall taps (2 per set)', 2, ARRAY['MW04', 'MW05', 'MW06', 'MW08JL']),
  ('P027006-01-20', '20mm Fitting for wall taps MW11 (2 per set)', 2, ARRAY['MW11']),
  ('DMW-Part1', 'Mounting for MW03 (Old Type)', 1, ARRAY['MW07TS', 'MW03']),
  ('MW03-FIN Display Fitting', 'MW03-FIN Display Fitting', 1, ARRAY['MW03-FIN']),
  ('MW07TS-FIN Display Fitting', 'MW07TS-FIN Display Fitting', 1, ARRAY['MW07TS']),
  ('DIV-FIT', 'Display board mount for diverter Handle MW07TS', 1, ARRAY['MW07TS']),
  ('838076', 'Brass fitting for spout and shower arms', 1, ARRAY['MA02', 'MA11', 'MA07', 'MA09', 'MS07', 'MS08', 'MS09', 'MS11', 'MS16']),
  ('DMQ04', 'MW11 cut-down spindles for display board', 2, ARRAY['MW11']),
  ('MPWT01', 'MPWT01 fitting for showers', 1, ARRAY['MZ0704', 'MZ0704-R', 'MZ0706', 'MZ0706-R', 'MZ0904', 'MZ0904-R', 'MZ0906', 'MZ0906-R', 'MZ06', 'MZ06-R', 'MZ08', 'MZ08-R']);
